// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="particlemaster,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.470600,HLS_SYN_LAT=7404,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=7873,HLS_SYN_FF=758258,HLS_SYN_LUT=305289}" *)

module particlemaster (
        clk,
        reset,
        start,
        maximum,
        calculate,
        setup,
        negativeFormula,
        c1,
        c2,
        finalx1,
        finalx2,
        complete,
        cognitive,
        social,
        x1_global,
        x2_global,
        x1_p1,
        x2_p1,
        ready_p1,
        x1_p2,
        x2_p2,
        ready_p2,
        x1_p3,
        x2_p3,
        ready_p3,
        x1_p4,
        x2_p4,
        ready_p4,
        x1_p5,
        x2_p5,
        ready_p5,
        x1_p6,
        x2_p6,
        ready_p6,
        x1_p7,
        x2_p7,
        ready_p7,
        x1_p8,
        x2_p8,
        ready_p8,
        x1_p9,
        x2_p9,
        ready_p9,
        x1_p10,
        x2_p10,
        ready_p10
);


input   clk;
input   reset;
input   start;
output   maximum;
output   calculate;
output   setup;
input   negativeFormula;
input  [31:0] c1;
input  [31:0] c2;
output  [31:0] finalx1;
output  [31:0] finalx2;
output   complete;
output  [31:0] cognitive;
output  [31:0] social;
output  [31:0] x1_global;
output  [31:0] x2_global;
input  [31:0] x1_p1;
input  [31:0] x2_p1;
input   ready_p1;
input  [31:0] x1_p2;
input  [31:0] x2_p2;
input   ready_p2;
input  [31:0] x1_p3;
input  [31:0] x2_p3;
input   ready_p3;
input  [31:0] x1_p4;
input  [31:0] x2_p4;
input   ready_p4;
input  [31:0] x1_p5;
input  [31:0] x2_p5;
input   ready_p5;
input  [31:0] x1_p6;
input  [31:0] x2_p6;
input   ready_p6;
input  [31:0] x1_p7;
input  [31:0] x2_p7;
input   ready_p7;
input  [31:0] x1_p8;
input  [31:0] x2_p8;
input   ready_p8;
input  [31:0] x1_p9;
input  [31:0] x2_p9;
input   ready_p9;
input  [31:0] x1_p10;
input  [31:0] x2_p10;
input   ready_p10;

reg maximum;
reg calculate;
reg setup;
reg[31:0] finalx1;
reg[31:0] finalx2;
reg complete;
reg[31:0] cognitive;
reg[31:0] social;
reg[31:0] x1_global;
reg[31:0] x2_global;

wire   [0:0] particlemaster_ss_load_fu_490_p1;
wire   [1:0] ap_CS_fsm;
wire    grp_particlemaster_ReadCalculations_fu_254_calculate;
wire    grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_finalx1;
wire    grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_finalx2;
wire    grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld;
wire    grp_particlemaster_ReadCalculations_fu_254_complete;
wire    grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_x1_global;
wire    grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_x2_global;
wire    grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o;
wire    grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o;
wire    grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld;
wire    grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula;
wire   [31:0] grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o;
wire    grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld;
wire    grp_particlemaster_Setup_fu_384_maximum;
wire    grp_particlemaster_Setup_fu_384_maximum_ap_vld;
wire    grp_particlemaster_Setup_fu_384_setup;
wire    grp_particlemaster_Setup_fu_384_setup_ap_vld;
wire   [31:0] grp_particlemaster_Setup_fu_384_cognitive;
wire    grp_particlemaster_Setup_fu_384_cognitive_ap_vld;
wire   [31:0] grp_particlemaster_Setup_fu_384_social;
wire    grp_particlemaster_Setup_fu_384_social_ap_vld;
wire    grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i;
wire    grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o;
wire    grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld;
wire    grp_particlemaster_Setup_fu_384_particlemaster_negFormula;
wire    grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld;
wire   [31:0] grp_particlemaster_Setup_fu_384_particlemaster_iterations;
wire    grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld;
wire    ap_CS_fsm_state2;
reg   [0:0] particlemaster_setupDone;
reg   [31:0] particlemaster_x1_best;
reg   [31:0] particlemaster_x2_best;
reg   [0:0] particlemaster_negFormula;
reg   [31:0] particlemaster_iterations;

particlemaster_ReadCalculations grp_particlemaster_ReadCalculations_fu_254(
    .ap_clk(clk),
    .ap_rst(reset),
    .calculate(grp_particlemaster_ReadCalculations_fu_254_calculate),
    .calculate_ap_vld(grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld),
    .finalx1(grp_particlemaster_ReadCalculations_fu_254_finalx1),
    .finalx1_ap_vld(grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld),
    .finalx2(grp_particlemaster_ReadCalculations_fu_254_finalx2),
    .finalx2_ap_vld(grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld),
    .complete(grp_particlemaster_ReadCalculations_fu_254_complete),
    .complete_ap_vld(grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld),
    .x1_global(grp_particlemaster_ReadCalculations_fu_254_x1_global),
    .x1_global_ap_vld(grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld),
    .x2_global(grp_particlemaster_ReadCalculations_fu_254_x2_global),
    .x2_global_ap_vld(grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld),
    .x1_p1(x1_p1),
    .x2_p1(x2_p1),
    .ready_p1(ready_p1),
    .x1_p2(x1_p2),
    .x2_p2(x2_p2),
    .ready_p2(ready_p2),
    .x1_p3(x1_p3),
    .x2_p3(x2_p3),
    .ready_p3(ready_p3),
    .x1_p4(x1_p4),
    .x2_p4(x2_p4),
    .ready_p4(ready_p4),
    .x1_p5(x1_p5),
    .x2_p5(x2_p5),
    .ready_p5(ready_p5),
    .x1_p6(x1_p6),
    .x2_p6(x2_p6),
    .ready_p6(ready_p6),
    .x1_p7(x1_p7),
    .x2_p7(x2_p7),
    .ready_p7(ready_p7),
    .x1_p8(x1_p8),
    .x2_p8(x2_p8),
    .ready_p8(ready_p8),
    .x1_p9(x1_p9),
    .x2_p9(x2_p9),
    .ready_p9(ready_p9),
    .x1_p10(x1_p10),
    .x2_p10(x2_p10),
    .ready_p10(ready_p10),
    .particlemaster_x1_best_i(particlemaster_x1_best),
    .particlemaster_x1_best_o(grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o),
    .particlemaster_x1_best_o_ap_vld(grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld),
    .particlemaster_x2_best_i(particlemaster_x2_best),
    .particlemaster_x2_best_o(grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o),
    .particlemaster_x2_best_o_ap_vld(grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld),
    .particlemaster_negFormula(grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula),
    .particlemaster_iterations_i(particlemaster_iterations),
    .particlemaster_iterations_o(grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o),
    .particlemaster_iterations_o_ap_vld(grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld)
);

particlemaster_Setup grp_particlemaster_Setup_fu_384(
    .ap_clk(clk),
    .ap_rst(reset),
    .start(start),
    .maximum(grp_particlemaster_Setup_fu_384_maximum),
    .maximum_ap_vld(grp_particlemaster_Setup_fu_384_maximum_ap_vld),
    .setup(grp_particlemaster_Setup_fu_384_setup),
    .setup_ap_vld(grp_particlemaster_Setup_fu_384_setup_ap_vld),
    .negativeFormula(negativeFormula),
    .c1(c1),
    .c2(c2),
    .cognitive(grp_particlemaster_Setup_fu_384_cognitive),
    .cognitive_ap_vld(grp_particlemaster_Setup_fu_384_cognitive_ap_vld),
    .social(grp_particlemaster_Setup_fu_384_social),
    .social_ap_vld(grp_particlemaster_Setup_fu_384_social_ap_vld),
    .particlemaster_setupDone_i(grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i),
    .particlemaster_setupDone_o(grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o),
    .particlemaster_setupDone_o_ap_vld(grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld),
    .particlemaster_negFormula(grp_particlemaster_Setup_fu_384_particlemaster_negFormula),
    .particlemaster_negFormula_ap_vld(grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld),
    .particlemaster_iterations(grp_particlemaster_Setup_fu_384_particlemaster_iterations),
    .particlemaster_iterations_ap_vld(grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld)
);

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld)) begin
        calculate <= grp_particlemaster_ReadCalculations_fu_254_calculate;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_cognitive_ap_vld)) begin
        cognitive <= grp_particlemaster_Setup_fu_384_cognitive;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld)) begin
        complete <= grp_particlemaster_ReadCalculations_fu_254_complete;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld)) begin
        finalx1 <= grp_particlemaster_ReadCalculations_fu_254_finalx1;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld)) begin
        finalx2 <= grp_particlemaster_ReadCalculations_fu_254_finalx2;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_maximum_ap_vld)) begin
        maximum <= grp_particlemaster_Setup_fu_384_maximum;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld)) begin
        particlemaster_iterations <= grp_particlemaster_Setup_fu_384_particlemaster_iterations;
    end else if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld)) begin
        particlemaster_iterations <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld)) begin
        particlemaster_negFormula <= grp_particlemaster_Setup_fu_384_particlemaster_negFormula;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld)) begin
        particlemaster_setupDone <= grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld)) begin
        particlemaster_x1_best <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld)) begin
        particlemaster_x2_best <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_setup_ap_vld)) begin
        setup <= grp_particlemaster_Setup_fu_384_setup;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_Setup_fu_384_social_ap_vld)) begin
        social <= grp_particlemaster_Setup_fu_384_social;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld)) begin
        x1_global <= grp_particlemaster_ReadCalculations_fu_254_x1_global;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld)) begin
        x2_global <= grp_particlemaster_ReadCalculations_fu_254_x2_global;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula = particlemaster_negFormula;

assign grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i = particlemaster_setupDone;

assign particlemaster_ss_load_fu_490_p1 = 1'd0;

endmodule //particlemaster
