-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity floatPrototypec is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    float1 : IN STD_LOGIC_VECTOR (31 downto 0);
    float2 : IN STD_LOGIC_VECTOR (31 downto 0);
    float3 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of floatPrototypec is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "floatPrototypec,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.702000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=179,HLS_SYN_LUT=348}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal floatPrototypec_s_load_fu_74_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal grp_floatPrototypec_multiply_fu_60_float3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_floatPrototypec_multiply_fu_60_float3_ap_vld : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";

    component floatPrototypec_multiply IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        float1 : IN STD_LOGIC_VECTOR (31 downto 0);
        float2 : IN STD_LOGIC_VECTOR (31 downto 0);
        float3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        float3_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_floatPrototypec_multiply_fu_60 : component floatPrototypec_multiply
    port map (
        ap_clk => clk,
        ap_rst => reset,
        float1 => float1,
        float2 => float2,
        float3 => grp_floatPrototypec_multiply_fu_60_float3,
        float3_ap_vld => grp_floatPrototypec_multiply_fu_60_float3_ap_vld);





    float3_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_floatPrototypec_multiply_fu_60_float3_ap_vld)) then 
                float3 <= grp_floatPrototypec_multiply_fu_60_float3;
            end if; 
        end if;
    end process;

    ap_CS_fsm <= ap_const_lv2_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    floatPrototypec_s_load_fu_74_p1 <= ap_const_lv1_0;
end behav;
