-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity particlemaster is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    start : IN STD_LOGIC;
    maximum : OUT STD_LOGIC;
    calculate : OUT STD_LOGIC;
    setup : OUT STD_LOGIC;
    negativeFormula : IN STD_LOGIC;
    c1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c2 : IN STD_LOGIC_VECTOR (31 downto 0);
    finalx1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    finalx2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    complete : OUT STD_LOGIC;
    cognitive : OUT STD_LOGIC_VECTOR (31 downto 0);
    social : OUT STD_LOGIC_VECTOR (31 downto 0);
    x1_global : OUT STD_LOGIC_VECTOR (31 downto 0);
    x2_global : OUT STD_LOGIC_VECTOR (31 downto 0);
    x1_p1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p1 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p1 : IN STD_LOGIC;
    x1_p2 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p2 : IN STD_LOGIC;
    x1_p3 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p3 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p3 : IN STD_LOGIC;
    x1_p4 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p4 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p4 : IN STD_LOGIC;
    x1_p5 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p5 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p5 : IN STD_LOGIC;
    x1_p6 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p6 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p6 : IN STD_LOGIC;
    x1_p7 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p7 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p7 : IN STD_LOGIC;
    x1_p8 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p8 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p8 : IN STD_LOGIC;
    x1_p9 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p9 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p9 : IN STD_LOGIC;
    x1_p10 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_p10 : IN STD_LOGIC_VECTOR (31 downto 0);
    ready_p10 : IN STD_LOGIC );
end;


architecture behav of particlemaster is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "particlemaster,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.470600,HLS_SYN_LAT=7404,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=7873,HLS_SYN_FF=758258,HLS_SYN_LUT=305289}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal particlemaster_ss_load_fu_490_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal grp_particlemaster_ReadCalculations_fu_254_calculate : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_finalx1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_finalx2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_complete : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_x1_global : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_x2_global : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula : STD_LOGIC;
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_maximum : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_maximum_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_setup : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_setup_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_cognitive : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_Setup_fu_384_cognitive_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_social : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_Setup_fu_384_social_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_negFormula : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld : STD_LOGIC;
    signal grp_particlemaster_Setup_fu_384_particlemaster_iterations : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal particlemaster_setupDone : STD_LOGIC_VECTOR (0 downto 0);
    signal particlemaster_x1_best : STD_LOGIC_VECTOR (31 downto 0);
    signal particlemaster_x2_best : STD_LOGIC_VECTOR (31 downto 0);
    signal particlemaster_negFormula : STD_LOGIC_VECTOR (0 downto 0);
    signal particlemaster_iterations : STD_LOGIC_VECTOR (31 downto 0);

    component particlemaster_ReadCalculations IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        calculate : OUT STD_LOGIC;
        calculate_ap_vld : OUT STD_LOGIC;
        finalx1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        finalx1_ap_vld : OUT STD_LOGIC;
        finalx2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        finalx2_ap_vld : OUT STD_LOGIC;
        complete : OUT STD_LOGIC;
        complete_ap_vld : OUT STD_LOGIC;
        x1_global : OUT STD_LOGIC_VECTOR (31 downto 0);
        x1_global_ap_vld : OUT STD_LOGIC;
        x2_global : OUT STD_LOGIC_VECTOR (31 downto 0);
        x2_global_ap_vld : OUT STD_LOGIC;
        x1_p1 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p1 : IN STD_LOGIC;
        x1_p2 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p2 : IN STD_LOGIC;
        x1_p3 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p3 : IN STD_LOGIC;
        x1_p4 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p4 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p4 : IN STD_LOGIC;
        x1_p5 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p5 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p5 : IN STD_LOGIC;
        x1_p6 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p6 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p6 : IN STD_LOGIC;
        x1_p7 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p7 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p7 : IN STD_LOGIC;
        x1_p8 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p8 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p8 : IN STD_LOGIC;
        x1_p9 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p9 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p9 : IN STD_LOGIC;
        x1_p10 : IN STD_LOGIC_VECTOR (31 downto 0);
        x2_p10 : IN STD_LOGIC_VECTOR (31 downto 0);
        ready_p10 : IN STD_LOGIC;
        particlemaster_x1_best_i : IN STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_x1_best_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_x1_best_o_ap_vld : OUT STD_LOGIC;
        particlemaster_x2_best_i : IN STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_x2_best_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_x2_best_o_ap_vld : OUT STD_LOGIC;
        particlemaster_negFormula : IN STD_LOGIC;
        particlemaster_iterations_i : IN STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_iterations_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_iterations_o_ap_vld : OUT STD_LOGIC );
    end component;


    component particlemaster_Setup IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        start : IN STD_LOGIC;
        maximum : OUT STD_LOGIC;
        maximum_ap_vld : OUT STD_LOGIC;
        setup : OUT STD_LOGIC;
        setup_ap_vld : OUT STD_LOGIC;
        negativeFormula : IN STD_LOGIC;
        c1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c2 : IN STD_LOGIC_VECTOR (31 downto 0);
        cognitive : OUT STD_LOGIC_VECTOR (31 downto 0);
        cognitive_ap_vld : OUT STD_LOGIC;
        social : OUT STD_LOGIC_VECTOR (31 downto 0);
        social_ap_vld : OUT STD_LOGIC;
        particlemaster_setupDone_i : IN STD_LOGIC;
        particlemaster_setupDone_o : OUT STD_LOGIC;
        particlemaster_setupDone_o_ap_vld : OUT STD_LOGIC;
        particlemaster_negFormula : OUT STD_LOGIC;
        particlemaster_negFormula_ap_vld : OUT STD_LOGIC;
        particlemaster_iterations : OUT STD_LOGIC_VECTOR (31 downto 0);
        particlemaster_iterations_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_particlemaster_ReadCalculations_fu_254 : component particlemaster_ReadCalculations
    port map (
        ap_clk => clk,
        ap_rst => reset,
        calculate => grp_particlemaster_ReadCalculations_fu_254_calculate,
        calculate_ap_vld => grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld,
        finalx1 => grp_particlemaster_ReadCalculations_fu_254_finalx1,
        finalx1_ap_vld => grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld,
        finalx2 => grp_particlemaster_ReadCalculations_fu_254_finalx2,
        finalx2_ap_vld => grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld,
        complete => grp_particlemaster_ReadCalculations_fu_254_complete,
        complete_ap_vld => grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld,
        x1_global => grp_particlemaster_ReadCalculations_fu_254_x1_global,
        x1_global_ap_vld => grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld,
        x2_global => grp_particlemaster_ReadCalculations_fu_254_x2_global,
        x2_global_ap_vld => grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld,
        x1_p1 => x1_p1,
        x2_p1 => x2_p1,
        ready_p1 => ready_p1,
        x1_p2 => x1_p2,
        x2_p2 => x2_p2,
        ready_p2 => ready_p2,
        x1_p3 => x1_p3,
        x2_p3 => x2_p3,
        ready_p3 => ready_p3,
        x1_p4 => x1_p4,
        x2_p4 => x2_p4,
        ready_p4 => ready_p4,
        x1_p5 => x1_p5,
        x2_p5 => x2_p5,
        ready_p5 => ready_p5,
        x1_p6 => x1_p6,
        x2_p6 => x2_p6,
        ready_p6 => ready_p6,
        x1_p7 => x1_p7,
        x2_p7 => x2_p7,
        ready_p7 => ready_p7,
        x1_p8 => x1_p8,
        x2_p8 => x2_p8,
        ready_p8 => ready_p8,
        x1_p9 => x1_p9,
        x2_p9 => x2_p9,
        ready_p9 => ready_p9,
        x1_p10 => x1_p10,
        x2_p10 => x2_p10,
        ready_p10 => ready_p10,
        particlemaster_x1_best_i => particlemaster_x1_best,
        particlemaster_x1_best_o => grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o,
        particlemaster_x1_best_o_ap_vld => grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld,
        particlemaster_x2_best_i => particlemaster_x2_best,
        particlemaster_x2_best_o => grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o,
        particlemaster_x2_best_o_ap_vld => grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld,
        particlemaster_negFormula => grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula,
        particlemaster_iterations_i => particlemaster_iterations,
        particlemaster_iterations_o => grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o,
        particlemaster_iterations_o_ap_vld => grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld);

    grp_particlemaster_Setup_fu_384 : component particlemaster_Setup
    port map (
        ap_clk => clk,
        ap_rst => reset,
        start => start,
        maximum => grp_particlemaster_Setup_fu_384_maximum,
        maximum_ap_vld => grp_particlemaster_Setup_fu_384_maximum_ap_vld,
        setup => grp_particlemaster_Setup_fu_384_setup,
        setup_ap_vld => grp_particlemaster_Setup_fu_384_setup_ap_vld,
        negativeFormula => negativeFormula,
        c1 => c1,
        c2 => c2,
        cognitive => grp_particlemaster_Setup_fu_384_cognitive,
        cognitive_ap_vld => grp_particlemaster_Setup_fu_384_cognitive_ap_vld,
        social => grp_particlemaster_Setup_fu_384_social,
        social_ap_vld => grp_particlemaster_Setup_fu_384_social_ap_vld,
        particlemaster_setupDone_i => grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i,
        particlemaster_setupDone_o => grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o,
        particlemaster_setupDone_o_ap_vld => grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld,
        particlemaster_negFormula => grp_particlemaster_Setup_fu_384_particlemaster_negFormula,
        particlemaster_negFormula_ap_vld => grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld,
        particlemaster_iterations => grp_particlemaster_Setup_fu_384_particlemaster_iterations,
        particlemaster_iterations_ap_vld => grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld);





    calculate_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_calculate_ap_vld)) then 
                calculate <= grp_particlemaster_ReadCalculations_fu_254_calculate;
            end if; 
        end if;
    end process;


    cognitive_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_cognitive_ap_vld)) then 
                cognitive <= grp_particlemaster_Setup_fu_384_cognitive;
            end if; 
        end if;
    end process;


    complete_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_complete_ap_vld)) then 
                complete <= grp_particlemaster_ReadCalculations_fu_254_complete;
            end if; 
        end if;
    end process;


    finalx1_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_finalx1_ap_vld)) then 
                finalx1 <= grp_particlemaster_ReadCalculations_fu_254_finalx1;
            end if; 
        end if;
    end process;


    finalx2_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_finalx2_ap_vld)) then 
                finalx2 <= grp_particlemaster_ReadCalculations_fu_254_finalx2;
            end if; 
        end if;
    end process;


    maximum_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_maximum_ap_vld)) then 
                maximum <= grp_particlemaster_Setup_fu_384_maximum;
            end if; 
        end if;
    end process;


    particlemaster_iterations_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_particlemaster_iterations_ap_vld)) then 
                particlemaster_iterations <= grp_particlemaster_Setup_fu_384_particlemaster_iterations;
            elsif ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o_ap_vld)) then 
                particlemaster_iterations <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_iterations_o;
            end if; 
        end if;
    end process;


    particlemaster_negFormula_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_particlemaster_negFormula_ap_vld)) then 
                particlemaster_negFormula <= (0=>grp_particlemaster_Setup_fu_384_particlemaster_negFormula, others=>'-');
            end if; 
        end if;
    end process;


    particlemaster_setupDone_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o_ap_vld)) then 
                particlemaster_setupDone <= (0=>grp_particlemaster_Setup_fu_384_particlemaster_setupDone_o, others=>'-');
            end if; 
        end if;
    end process;


    particlemaster_x1_best_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o_ap_vld)) then 
                particlemaster_x1_best <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_x1_best_o;
            end if; 
        end if;
    end process;


    particlemaster_x2_best_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o_ap_vld)) then 
                particlemaster_x2_best <= grp_particlemaster_ReadCalculations_fu_254_particlemaster_x2_best_o;
            end if; 
        end if;
    end process;


    setup_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_setup_ap_vld)) then 
                setup <= grp_particlemaster_Setup_fu_384_setup;
            end if; 
        end if;
    end process;


    social_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_Setup_fu_384_social_ap_vld)) then 
                social <= grp_particlemaster_Setup_fu_384_social;
            end if; 
        end if;
    end process;


    x1_global_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_x1_global_ap_vld)) then 
                x1_global <= grp_particlemaster_ReadCalculations_fu_254_x1_global;
            end if; 
        end if;
    end process;


    x2_global_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_particlemaster_ReadCalculations_fu_254_x2_global_ap_vld)) then 
                x2_global <= grp_particlemaster_ReadCalculations_fu_254_x2_global;
            end if; 
        end if;
    end process;

    ap_CS_fsm <= ap_const_lv2_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    grp_particlemaster_ReadCalculations_fu_254_particlemaster_negFormula <= particlemaster_negFormula(0);
    grp_particlemaster_Setup_fu_384_particlemaster_setupDone_i <= particlemaster_setupDone(0);
    particlemaster_ss_load_fu_490_p1 <= ap_const_lv1_0;
end behav;
