-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity psosc is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    start : IN STD_LOGIC;
    negativeFormula : IN STD_LOGIC;
    c1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c2 : IN STD_LOGIC_VECTOR (31 downto 0);
    finalx1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    finalx2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    complete : OUT STD_LOGIC );
end;


architecture behav of psosc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "psosc,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.916600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=10552,HLS_SYN_FF=1015445,HLS_SYN_LUT=407260}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal psosc_p_x1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_x1_ce0 : STD_LOGIC;
    signal psosc_p_x1_we0 : STD_LOGIC;
    signal psosc_p_x1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_x2_ce0 : STD_LOGIC;
    signal psosc_p_x2_we0 : STD_LOGIC;
    signal psosc_p_x2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_v1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_v1_ce0 : STD_LOGIC;
    signal psosc_p_v1_we0 : STD_LOGIC;
    signal psosc_p_v1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_v1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_v2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_v2_ce0 : STD_LOGIC;
    signal psosc_p_v2_we0 : STD_LOGIC;
    signal psosc_p_v2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_v2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x1_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_x1_best_ce0 : STD_LOGIC;
    signal psosc_p_x1_best_we0 : STD_LOGIC;
    signal psosc_p_x1_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x1_best_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x2_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal psosc_p_x2_best_ce0 : STD_LOGIC;
    signal psosc_p_x2_best_we0 : STD_LOGIC;
    signal psosc_p_x2_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_p_x2_best_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_ssdm_thread_load_fu_266_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal grp_psosc_Execute_fu_130_finalx1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_finalx1_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_finalx2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_finalx2_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_complete : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_complete_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_setupDone : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_calculationDone_i : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_calculationDone_o : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_negFormula : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_iterations : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_iterations_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_x1_global_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_x2_global_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x1_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x1_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x2_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x2_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_v1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_v1_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_v1_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_v1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_v2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_v2_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_v2_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_v2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x1_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x1_best_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x1_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x2_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x2_best_we0 : STD_LOGIC;
    signal grp_psosc_Execute_fu_130_psosc_p_x2_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_complete : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_complete_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_setupDone_i : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_setupDone_o : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_negFormula : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_c1_cog : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_c2_soc : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_w : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_w_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_ax : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_ax_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_av : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_av_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_x1_global : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_x2_global : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x1_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x1_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x2_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x2_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_v1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_v1_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_v1_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_v1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_v2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_v2_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_v2_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_v2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x1_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x1_best_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x1_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x2_best_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x2_best_we0 : STD_LOGIC;
    signal grp_psosc_Setup_fu_210_psosc_p_x2_best_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal psosc_setupDone : STD_LOGIC_VECTOR (0 downto 0);
    signal psosc_calculationDone : STD_LOGIC_VECTOR (0 downto 0);
    signal psosc_negFormula : STD_LOGIC_VECTOR (0 downto 0);
    signal psosc_w : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_x1_global : STD_LOGIC_VECTOR (31 downto 0);
    signal psosc_x2_global : STD_LOGIC_VECTOR (31 downto 0);

    component psosc_Execute IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        start : IN STD_LOGIC;
        c1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c2 : IN STD_LOGIC_VECTOR (31 downto 0);
        finalx1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        finalx1_ap_vld : OUT STD_LOGIC;
        finalx2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        finalx2_ap_vld : OUT STD_LOGIC;
        complete : OUT STD_LOGIC;
        complete_ap_vld : OUT STD_LOGIC;
        psosc_setupDone : IN STD_LOGIC;
        psosc_calculationDone_i : IN STD_LOGIC;
        psosc_calculationDone_o : OUT STD_LOGIC;
        psosc_calculationDone_o_ap_vld : OUT STD_LOGIC;
        psosc_negFormula : IN STD_LOGIC;
        psosc_w : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_iterations : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_iterations_ap_vld : OUT STD_LOGIC;
        psosc_x1_global_i : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_x1_global_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_x1_global_o_ap_vld : OUT STD_LOGIC;
        psosc_x2_global_i : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_x2_global_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_x2_global_o_ap_vld : OUT STD_LOGIC;
        psosc_p_x1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x1_ce0 : OUT STD_LOGIC;
        psosc_p_x1_we0 : OUT STD_LOGIC;
        psosc_p_x1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x2_ce0 : OUT STD_LOGIC;
        psosc_p_x2_we0 : OUT STD_LOGIC;
        psosc_p_x2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_v1_ce0 : OUT STD_LOGIC;
        psosc_p_v1_we0 : OUT STD_LOGIC;
        psosc_p_v1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_v2_ce0 : OUT STD_LOGIC;
        psosc_p_v2_we0 : OUT STD_LOGIC;
        psosc_p_v2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x1_best_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x1_best_ce0 : OUT STD_LOGIC;
        psosc_p_x1_best_we0 : OUT STD_LOGIC;
        psosc_p_x1_best_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x1_best_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_best_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x2_best_ce0 : OUT STD_LOGIC;
        psosc_p_x2_best_we0 : OUT STD_LOGIC;
        psosc_p_x2_best_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_best_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component psosc_Setup IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        start : IN STD_LOGIC;
        negativeFormula : IN STD_LOGIC;
        c1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c2 : IN STD_LOGIC_VECTOR (31 downto 0);
        complete : OUT STD_LOGIC;
        complete_ap_vld : OUT STD_LOGIC;
        psosc_setupDone_i : IN STD_LOGIC;
        psosc_setupDone_o : OUT STD_LOGIC;
        psosc_setupDone_o_ap_vld : OUT STD_LOGIC;
        psosc_negFormula : OUT STD_LOGIC;
        psosc_negFormula_ap_vld : OUT STD_LOGIC;
        psosc_c1_cog : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_c1_cog_ap_vld : OUT STD_LOGIC;
        psosc_c2_soc : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_c2_soc_ap_vld : OUT STD_LOGIC;
        psosc_w : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_w_ap_vld : OUT STD_LOGIC;
        psosc_ax : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_ax_ap_vld : OUT STD_LOGIC;
        psosc_av : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_av_ap_vld : OUT STD_LOGIC;
        psosc_x1_global : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_x1_global_ap_vld : OUT STD_LOGIC;
        psosc_x2_global : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_x2_global_ap_vld : OUT STD_LOGIC;
        psosc_p_x1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x1_ce0 : OUT STD_LOGIC;
        psosc_p_x1_we0 : OUT STD_LOGIC;
        psosc_p_x1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x2_ce0 : OUT STD_LOGIC;
        psosc_p_x2_we0 : OUT STD_LOGIC;
        psosc_p_x2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_v1_ce0 : OUT STD_LOGIC;
        psosc_p_v1_we0 : OUT STD_LOGIC;
        psosc_p_v1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_v2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_v2_ce0 : OUT STD_LOGIC;
        psosc_p_v2_we0 : OUT STD_LOGIC;
        psosc_p_v2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x1_best_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x1_best_ce0 : OUT STD_LOGIC;
        psosc_p_x1_best_we0 : OUT STD_LOGIC;
        psosc_p_x1_best_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        psosc_p_x2_best_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        psosc_p_x2_best_ce0 : OUT STD_LOGIC;
        psosc_p_x2_best_we0 : OUT STD_LOGIC;
        psosc_p_x2_best_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component psosc_psosc_p_x1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    psosc_p_x1_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_x1_address0,
        ce0 => psosc_p_x1_ce0,
        we0 => psosc_p_x1_we0,
        d0 => psosc_p_x1_d0,
        q0 => psosc_p_x1_q0);

    psosc_p_x2_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_x2_address0,
        ce0 => psosc_p_x2_ce0,
        we0 => psosc_p_x2_we0,
        d0 => psosc_p_x2_d0,
        q0 => psosc_p_x2_q0);

    psosc_p_v1_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_v1_address0,
        ce0 => psosc_p_v1_ce0,
        we0 => psosc_p_v1_we0,
        d0 => psosc_p_v1_d0,
        q0 => psosc_p_v1_q0);

    psosc_p_v2_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_v2_address0,
        ce0 => psosc_p_v2_ce0,
        we0 => psosc_p_v2_we0,
        d0 => psosc_p_v2_d0,
        q0 => psosc_p_v2_q0);

    psosc_p_x1_best_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_x1_best_address0,
        ce0 => psosc_p_x1_best_ce0,
        we0 => psosc_p_x1_best_we0,
        d0 => psosc_p_x1_best_d0,
        q0 => psosc_p_x1_best_q0);

    psosc_p_x2_best_U : component psosc_psosc_p_x1
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => clk,
        reset => reset,
        address0 => psosc_p_x2_best_address0,
        ce0 => psosc_p_x2_best_ce0,
        we0 => psosc_p_x2_best_we0,
        d0 => psosc_p_x2_best_d0,
        q0 => psosc_p_x2_best_q0);

    grp_psosc_Execute_fu_130 : component psosc_Execute
    port map (
        ap_clk => clk,
        ap_rst => reset,
        start => start,
        c1 => c1,
        c2 => c2,
        finalx1 => grp_psosc_Execute_fu_130_finalx1,
        finalx1_ap_vld => grp_psosc_Execute_fu_130_finalx1_ap_vld,
        finalx2 => grp_psosc_Execute_fu_130_finalx2,
        finalx2_ap_vld => grp_psosc_Execute_fu_130_finalx2_ap_vld,
        complete => grp_psosc_Execute_fu_130_complete,
        complete_ap_vld => grp_psosc_Execute_fu_130_complete_ap_vld,
        psosc_setupDone => grp_psosc_Execute_fu_130_psosc_setupDone,
        psosc_calculationDone_i => grp_psosc_Execute_fu_130_psosc_calculationDone_i,
        psosc_calculationDone_o => grp_psosc_Execute_fu_130_psosc_calculationDone_o,
        psosc_calculationDone_o_ap_vld => grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld,
        psosc_negFormula => grp_psosc_Execute_fu_130_psosc_negFormula,
        psosc_w => psosc_w,
        psosc_iterations => grp_psosc_Execute_fu_130_psosc_iterations,
        psosc_iterations_ap_vld => grp_psosc_Execute_fu_130_psosc_iterations_ap_vld,
        psosc_x1_global_i => psosc_x1_global,
        psosc_x1_global_o => grp_psosc_Execute_fu_130_psosc_x1_global_o,
        psosc_x1_global_o_ap_vld => grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld,
        psosc_x2_global_i => psosc_x2_global,
        psosc_x2_global_o => grp_psosc_Execute_fu_130_psosc_x2_global_o,
        psosc_x2_global_o_ap_vld => grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld,
        psosc_p_x1_address0 => grp_psosc_Execute_fu_130_psosc_p_x1_address0,
        psosc_p_x1_ce0 => grp_psosc_Execute_fu_130_psosc_p_x1_ce0,
        psosc_p_x1_we0 => grp_psosc_Execute_fu_130_psosc_p_x1_we0,
        psosc_p_x1_d0 => grp_psosc_Execute_fu_130_psosc_p_x1_d0,
        psosc_p_x1_q0 => psosc_p_x1_q0,
        psosc_p_x2_address0 => grp_psosc_Execute_fu_130_psosc_p_x2_address0,
        psosc_p_x2_ce0 => grp_psosc_Execute_fu_130_psosc_p_x2_ce0,
        psosc_p_x2_we0 => grp_psosc_Execute_fu_130_psosc_p_x2_we0,
        psosc_p_x2_d0 => grp_psosc_Execute_fu_130_psosc_p_x2_d0,
        psosc_p_x2_q0 => psosc_p_x2_q0,
        psosc_p_v1_address0 => grp_psosc_Execute_fu_130_psosc_p_v1_address0,
        psosc_p_v1_ce0 => grp_psosc_Execute_fu_130_psosc_p_v1_ce0,
        psosc_p_v1_we0 => grp_psosc_Execute_fu_130_psosc_p_v1_we0,
        psosc_p_v1_d0 => grp_psosc_Execute_fu_130_psosc_p_v1_d0,
        psosc_p_v1_q0 => psosc_p_v1_q0,
        psosc_p_v2_address0 => grp_psosc_Execute_fu_130_psosc_p_v2_address0,
        psosc_p_v2_ce0 => grp_psosc_Execute_fu_130_psosc_p_v2_ce0,
        psosc_p_v2_we0 => grp_psosc_Execute_fu_130_psosc_p_v2_we0,
        psosc_p_v2_d0 => grp_psosc_Execute_fu_130_psosc_p_v2_d0,
        psosc_p_v2_q0 => psosc_p_v2_q0,
        psosc_p_x1_best_address0 => grp_psosc_Execute_fu_130_psosc_p_x1_best_address0,
        psosc_p_x1_best_ce0 => grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0,
        psosc_p_x1_best_we0 => grp_psosc_Execute_fu_130_psosc_p_x1_best_we0,
        psosc_p_x1_best_d0 => grp_psosc_Execute_fu_130_psosc_p_x1_best_d0,
        psosc_p_x1_best_q0 => psosc_p_x1_best_q0,
        psosc_p_x2_best_address0 => grp_psosc_Execute_fu_130_psosc_p_x2_best_address0,
        psosc_p_x2_best_ce0 => grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0,
        psosc_p_x2_best_we0 => grp_psosc_Execute_fu_130_psosc_p_x2_best_we0,
        psosc_p_x2_best_d0 => grp_psosc_Execute_fu_130_psosc_p_x2_best_d0,
        psosc_p_x2_best_q0 => psosc_p_x2_best_q0);

    grp_psosc_Setup_fu_210 : component psosc_Setup
    port map (
        ap_clk => clk,
        ap_rst => reset,
        start => start,
        negativeFormula => negativeFormula,
        c1 => c1,
        c2 => c2,
        complete => grp_psosc_Setup_fu_210_complete,
        complete_ap_vld => grp_psosc_Setup_fu_210_complete_ap_vld,
        psosc_setupDone_i => grp_psosc_Setup_fu_210_psosc_setupDone_i,
        psosc_setupDone_o => grp_psosc_Setup_fu_210_psosc_setupDone_o,
        psosc_setupDone_o_ap_vld => grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld,
        psosc_negFormula => grp_psosc_Setup_fu_210_psosc_negFormula,
        psosc_negFormula_ap_vld => grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld,
        psosc_c1_cog => grp_psosc_Setup_fu_210_psosc_c1_cog,
        psosc_c1_cog_ap_vld => grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld,
        psosc_c2_soc => grp_psosc_Setup_fu_210_psosc_c2_soc,
        psosc_c2_soc_ap_vld => grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld,
        psosc_w => grp_psosc_Setup_fu_210_psosc_w,
        psosc_w_ap_vld => grp_psosc_Setup_fu_210_psosc_w_ap_vld,
        psosc_ax => grp_psosc_Setup_fu_210_psosc_ax,
        psosc_ax_ap_vld => grp_psosc_Setup_fu_210_psosc_ax_ap_vld,
        psosc_av => grp_psosc_Setup_fu_210_psosc_av,
        psosc_av_ap_vld => grp_psosc_Setup_fu_210_psosc_av_ap_vld,
        psosc_x1_global => grp_psosc_Setup_fu_210_psosc_x1_global,
        psosc_x1_global_ap_vld => grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld,
        psosc_x2_global => grp_psosc_Setup_fu_210_psosc_x2_global,
        psosc_x2_global_ap_vld => grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld,
        psosc_p_x1_address0 => grp_psosc_Setup_fu_210_psosc_p_x1_address0,
        psosc_p_x1_ce0 => grp_psosc_Setup_fu_210_psosc_p_x1_ce0,
        psosc_p_x1_we0 => grp_psosc_Setup_fu_210_psosc_p_x1_we0,
        psosc_p_x1_d0 => grp_psosc_Setup_fu_210_psosc_p_x1_d0,
        psosc_p_x2_address0 => grp_psosc_Setup_fu_210_psosc_p_x2_address0,
        psosc_p_x2_ce0 => grp_psosc_Setup_fu_210_psosc_p_x2_ce0,
        psosc_p_x2_we0 => grp_psosc_Setup_fu_210_psosc_p_x2_we0,
        psosc_p_x2_d0 => grp_psosc_Setup_fu_210_psosc_p_x2_d0,
        psosc_p_v1_address0 => grp_psosc_Setup_fu_210_psosc_p_v1_address0,
        psosc_p_v1_ce0 => grp_psosc_Setup_fu_210_psosc_p_v1_ce0,
        psosc_p_v1_we0 => grp_psosc_Setup_fu_210_psosc_p_v1_we0,
        psosc_p_v1_d0 => grp_psosc_Setup_fu_210_psosc_p_v1_d0,
        psosc_p_v2_address0 => grp_psosc_Setup_fu_210_psosc_p_v2_address0,
        psosc_p_v2_ce0 => grp_psosc_Setup_fu_210_psosc_p_v2_ce0,
        psosc_p_v2_we0 => grp_psosc_Setup_fu_210_psosc_p_v2_we0,
        psosc_p_v2_d0 => grp_psosc_Setup_fu_210_psosc_p_v2_d0,
        psosc_p_x1_best_address0 => grp_psosc_Setup_fu_210_psosc_p_x1_best_address0,
        psosc_p_x1_best_ce0 => grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0,
        psosc_p_x1_best_we0 => grp_psosc_Setup_fu_210_psosc_p_x1_best_we0,
        psosc_p_x1_best_d0 => grp_psosc_Setup_fu_210_psosc_p_x1_best_d0,
        psosc_p_x2_best_address0 => grp_psosc_Setup_fu_210_psosc_p_x2_best_address0,
        psosc_p_x2_best_ce0 => grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0,
        psosc_p_x2_best_we0 => grp_psosc_Setup_fu_210_psosc_p_x2_best_we0,
        psosc_p_x2_best_d0 => grp_psosc_Setup_fu_210_psosc_p_x2_best_d0);





    complete_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_complete_ap_vld)) then 
                complete <= grp_psosc_Setup_fu_210_complete;
            elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_complete_ap_vld)) then 
                complete <= grp_psosc_Execute_fu_130_complete;
            end if; 
        end if;
    end process;


    finalx1_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Execute_fu_130_finalx1_ap_vld)) then 
                finalx1 <= grp_psosc_Execute_fu_130_finalx1;
            end if; 
        end if;
    end process;


    finalx2_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Execute_fu_130_finalx2_ap_vld)) then 
                finalx2 <= grp_psosc_Execute_fu_130_finalx2;
            end if; 
        end if;
    end process;


    psosc_calculationDone_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld)) then 
                psosc_calculationDone <= (0=>grp_psosc_Execute_fu_130_psosc_calculationDone_o, others=>'-');
            end if; 
        end if;
    end process;


    psosc_negFormula_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld)) then 
                psosc_negFormula <= (0=>grp_psosc_Setup_fu_210_psosc_negFormula, others=>'-');
            end if; 
        end if;
    end process;


    psosc_setupDone_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld)) then 
                psosc_setupDone <= (0=>grp_psosc_Setup_fu_210_psosc_setupDone_o, others=>'-');
            end if; 
        end if;
    end process;


    psosc_w_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_w_ap_vld)) then 
                psosc_w <= grp_psosc_Setup_fu_210_psosc_w;
            end if; 
        end if;
    end process;


    psosc_x1_global_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld)) then 
                psosc_x1_global <= grp_psosc_Setup_fu_210_psosc_x1_global;
            elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld)) then 
                psosc_x1_global <= grp_psosc_Execute_fu_130_psosc_x1_global_o;
            end if; 
        end if;
    end process;


    psosc_x2_global_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld)) then 
                psosc_x2_global <= grp_psosc_Setup_fu_210_psosc_x2_global;
            elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld)) then 
                psosc_x2_global <= grp_psosc_Execute_fu_130_psosc_x2_global_o;
            end if; 
        end if;
    end process;

    ap_CS_fsm <= ap_const_lv2_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    grp_psosc_Execute_fu_130_psosc_calculationDone_i <= psosc_calculationDone(0);
    grp_psosc_Execute_fu_130_psosc_negFormula <= psosc_negFormula(0);
    grp_psosc_Execute_fu_130_psosc_setupDone <= psosc_setupDone(0);
    grp_psosc_Setup_fu_210_psosc_setupDone_i <= psosc_setupDone(0);

    psosc_p_v1_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v1_address0, grp_psosc_Execute_fu_130_psosc_p_v1_ce0, grp_psosc_Setup_fu_210_psosc_p_v1_address0, grp_psosc_Setup_fu_210_psosc_p_v1_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) then 
            psosc_p_v1_address0 <= grp_psosc_Setup_fu_210_psosc_p_v1_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) then 
            psosc_p_v1_address0 <= grp_psosc_Execute_fu_130_psosc_p_v1_address0;
        else 
            psosc_p_v1_address0 <= "XX";
        end if; 
    end process;


    psosc_p_v1_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v1_ce0, grp_psosc_Setup_fu_210_psosc_p_v1_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) then 
            psosc_p_v1_ce0 <= grp_psosc_Setup_fu_210_psosc_p_v1_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) then 
            psosc_p_v1_ce0 <= grp_psosc_Execute_fu_130_psosc_p_v1_ce0;
        else 
            psosc_p_v1_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_v1_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v1_ce0, grp_psosc_Execute_fu_130_psosc_p_v1_d0, grp_psosc_Setup_fu_210_psosc_p_v1_ce0, grp_psosc_Setup_fu_210_psosc_p_v1_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) then 
            psosc_p_v1_d0 <= grp_psosc_Setup_fu_210_psosc_p_v1_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) then 
            psosc_p_v1_d0 <= grp_psosc_Execute_fu_130_psosc_p_v1_d0;
        else 
            psosc_p_v1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_v1_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v1_ce0, grp_psosc_Execute_fu_130_psosc_p_v1_we0, grp_psosc_Setup_fu_210_psosc_p_v1_ce0, grp_psosc_Setup_fu_210_psosc_p_v1_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) then 
            psosc_p_v1_we0 <= grp_psosc_Setup_fu_210_psosc_p_v1_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) then 
            psosc_p_v1_we0 <= grp_psosc_Execute_fu_130_psosc_p_v1_we0;
        else 
            psosc_p_v1_we0 <= 'X';
        end if; 
    end process;


    psosc_p_v2_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v2_address0, grp_psosc_Execute_fu_130_psosc_p_v2_ce0, grp_psosc_Setup_fu_210_psosc_p_v2_address0, grp_psosc_Setup_fu_210_psosc_p_v2_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) then 
            psosc_p_v2_address0 <= grp_psosc_Setup_fu_210_psosc_p_v2_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) then 
            psosc_p_v2_address0 <= grp_psosc_Execute_fu_130_psosc_p_v2_address0;
        else 
            psosc_p_v2_address0 <= "XX";
        end if; 
    end process;


    psosc_p_v2_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v2_ce0, grp_psosc_Setup_fu_210_psosc_p_v2_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) then 
            psosc_p_v2_ce0 <= grp_psosc_Setup_fu_210_psosc_p_v2_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) then 
            psosc_p_v2_ce0 <= grp_psosc_Execute_fu_130_psosc_p_v2_ce0;
        else 
            psosc_p_v2_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_v2_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v2_ce0, grp_psosc_Execute_fu_130_psosc_p_v2_d0, grp_psosc_Setup_fu_210_psosc_p_v2_ce0, grp_psosc_Setup_fu_210_psosc_p_v2_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) then 
            psosc_p_v2_d0 <= grp_psosc_Setup_fu_210_psosc_p_v2_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) then 
            psosc_p_v2_d0 <= grp_psosc_Execute_fu_130_psosc_p_v2_d0;
        else 
            psosc_p_v2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_v2_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_v2_ce0, grp_psosc_Execute_fu_130_psosc_p_v2_we0, grp_psosc_Setup_fu_210_psosc_p_v2_ce0, grp_psosc_Setup_fu_210_psosc_p_v2_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) then 
            psosc_p_v2_we0 <= grp_psosc_Setup_fu_210_psosc_p_v2_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) then 
            psosc_p_v2_we0 <= grp_psosc_Execute_fu_130_psosc_p_v2_we0;
        else 
            psosc_p_v2_we0 <= 'X';
        end if; 
    end process;


    psosc_p_x1_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_address0, grp_psosc_Execute_fu_130_psosc_p_x1_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_address0, grp_psosc_Setup_fu_210_psosc_p_x1_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) then 
            psosc_p_x1_address0 <= grp_psosc_Setup_fu_210_psosc_p_x1_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) then 
            psosc_p_x1_address0 <= grp_psosc_Execute_fu_130_psosc_p_x1_address0;
        else 
            psosc_p_x1_address0 <= "XX";
        end if; 
    end process;


    psosc_p_x1_best_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_best_address0, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_best_address0, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_address0 <= grp_psosc_Setup_fu_210_psosc_p_x1_best_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_address0 <= grp_psosc_Execute_fu_130_psosc_p_x1_best_address0;
        else 
            psosc_p_x1_best_address0 <= "XX";
        end if; 
    end process;


    psosc_p_x1_best_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_ce0 <= grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_ce0 <= grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0;
        else 
            psosc_p_x1_best_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_x1_best_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0, grp_psosc_Execute_fu_130_psosc_p_x1_best_d0, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_best_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_d0 <= grp_psosc_Setup_fu_210_psosc_p_x1_best_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_d0 <= grp_psosc_Execute_fu_130_psosc_p_x1_best_d0;
        else 
            psosc_p_x1_best_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_x1_best_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0, grp_psosc_Execute_fu_130_psosc_p_x1_best_we0, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_best_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_we0 <= grp_psosc_Setup_fu_210_psosc_p_x1_best_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) then 
            psosc_p_x1_best_we0 <= grp_psosc_Execute_fu_130_psosc_p_x1_best_we0;
        else 
            psosc_p_x1_best_we0 <= 'X';
        end if; 
    end process;


    psosc_p_x1_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) then 
            psosc_p_x1_ce0 <= grp_psosc_Setup_fu_210_psosc_p_x1_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) then 
            psosc_p_x1_ce0 <= grp_psosc_Execute_fu_130_psosc_p_x1_ce0;
        else 
            psosc_p_x1_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_x1_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_ce0, grp_psosc_Execute_fu_130_psosc_p_x1_d0, grp_psosc_Setup_fu_210_psosc_p_x1_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) then 
            psosc_p_x1_d0 <= grp_psosc_Setup_fu_210_psosc_p_x1_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) then 
            psosc_p_x1_d0 <= grp_psosc_Execute_fu_130_psosc_p_x1_d0;
        else 
            psosc_p_x1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_x1_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x1_ce0, grp_psosc_Execute_fu_130_psosc_p_x1_we0, grp_psosc_Setup_fu_210_psosc_p_x1_ce0, grp_psosc_Setup_fu_210_psosc_p_x1_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) then 
            psosc_p_x1_we0 <= grp_psosc_Setup_fu_210_psosc_p_x1_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) then 
            psosc_p_x1_we0 <= grp_psosc_Execute_fu_130_psosc_p_x1_we0;
        else 
            psosc_p_x1_we0 <= 'X';
        end if; 
    end process;


    psosc_p_x2_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_address0, grp_psosc_Execute_fu_130_psosc_p_x2_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_address0, grp_psosc_Setup_fu_210_psosc_p_x2_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) then 
            psosc_p_x2_address0 <= grp_psosc_Setup_fu_210_psosc_p_x2_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) then 
            psosc_p_x2_address0 <= grp_psosc_Execute_fu_130_psosc_p_x2_address0;
        else 
            psosc_p_x2_address0 <= "XX";
        end if; 
    end process;


    psosc_p_x2_best_address0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_best_address0, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_best_address0, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_address0 <= grp_psosc_Setup_fu_210_psosc_p_x2_best_address0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_address0 <= grp_psosc_Execute_fu_130_psosc_p_x2_best_address0;
        else 
            psosc_p_x2_best_address0 <= "XX";
        end if; 
    end process;


    psosc_p_x2_best_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_ce0 <= grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_ce0 <= grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0;
        else 
            psosc_p_x2_best_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_x2_best_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0, grp_psosc_Execute_fu_130_psosc_p_x2_best_d0, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_best_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_d0 <= grp_psosc_Setup_fu_210_psosc_p_x2_best_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_d0 <= grp_psosc_Execute_fu_130_psosc_p_x2_best_d0;
        else 
            psosc_p_x2_best_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_x2_best_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0, grp_psosc_Execute_fu_130_psosc_p_x2_best_we0, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_best_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_we0 <= grp_psosc_Setup_fu_210_psosc_p_x2_best_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) then 
            psosc_p_x2_best_we0 <= grp_psosc_Execute_fu_130_psosc_p_x2_best_we0;
        else 
            psosc_p_x2_best_we0 <= 'X';
        end if; 
    end process;


    psosc_p_x2_ce0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_ce0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) then 
            psosc_p_x2_ce0 <= grp_psosc_Setup_fu_210_psosc_p_x2_ce0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) then 
            psosc_p_x2_ce0 <= grp_psosc_Execute_fu_130_psosc_p_x2_ce0;
        else 
            psosc_p_x2_ce0 <= 'X';
        end if; 
    end process;


    psosc_p_x2_d0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_ce0, grp_psosc_Execute_fu_130_psosc_p_x2_d0, grp_psosc_Setup_fu_210_psosc_p_x2_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_d0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) then 
            psosc_p_x2_d0 <= grp_psosc_Setup_fu_210_psosc_p_x2_d0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) then 
            psosc_p_x2_d0 <= grp_psosc_Execute_fu_130_psosc_p_x2_d0;
        else 
            psosc_p_x2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    psosc_p_x2_we0_assign_proc : process(grp_psosc_Execute_fu_130_psosc_p_x2_ce0, grp_psosc_Execute_fu_130_psosc_p_x2_we0, grp_psosc_Setup_fu_210_psosc_p_x2_ce0, grp_psosc_Setup_fu_210_psosc_p_x2_we0)
    begin
        if ((ap_const_logic_1 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) then 
            psosc_p_x2_we0 <= grp_psosc_Setup_fu_210_psosc_p_x2_we0;
        elsif ((ap_const_logic_1 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) then 
            psosc_p_x2_we0 <= grp_psosc_Execute_fu_130_psosc_p_x2_we0;
        else 
            psosc_p_x2_we0 <= 'X';
        end if; 
    end process;

    psosc_ssdm_thread_load_fu_266_p1 <= ap_const_lv1_0;
end behav;
