// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFLOATPROTOTYPEC_H
#define XFLOATPROTOTYPEC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfloatprototypec_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Slv0_BaseAddress;
} XFloatprototypec_Config;
#endif

typedef struct {
    u32 Slv0_BaseAddress;
    u32 IsReady;
} XFloatprototypec;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFloatprototypec_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFloatprototypec_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFloatprototypec_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFloatprototypec_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFloatprototypec_Initialize(XFloatprototypec *InstancePtr, u16 DeviceId);
XFloatprototypec_Config* XFloatprototypec_LookupConfig(u16 DeviceId);
int XFloatprototypec_CfgInitialize(XFloatprototypec *InstancePtr, XFloatprototypec_Config *ConfigPtr);
#else
int XFloatprototypec_Initialize(XFloatprototypec *InstancePtr, const char* InstanceName);
int XFloatprototypec_Release(XFloatprototypec *InstancePtr);
#endif


void XFloatprototypec_SetFloat1(XFloatprototypec *InstancePtr, u32 Data);
u32 XFloatprototypec_GetFloat1(XFloatprototypec *InstancePtr);
void XFloatprototypec_SetFloat2(XFloatprototypec *InstancePtr, u32 Data);
u32 XFloatprototypec_GetFloat2(XFloatprototypec *InstancePtr);
u32 XFloatprototypec_GetFloat3(XFloatprototypec *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
