// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="psosc,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.916600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=10552,HLS_SYN_FF=1015445,HLS_SYN_LUT=407260}" *)

module psosc (
        clk,
        reset,
        start,
        negativeFormula,
        c1,
        c2,
        finalx1,
        finalx2,
        complete
);


input   clk;
input   reset;
input   start;
input   negativeFormula;
input  [31:0] c1;
input  [31:0] c2;
output  [31:0] finalx1;
output  [31:0] finalx2;
output   complete;

reg[31:0] finalx1;
reg[31:0] finalx2;
reg complete;

reg   [1:0] psosc_p_x1_address0;
reg    psosc_p_x1_ce0;
reg    psosc_p_x1_we0;
reg   [31:0] psosc_p_x1_d0;
wire   [31:0] psosc_p_x1_q0;
reg   [1:0] psosc_p_x2_address0;
reg    psosc_p_x2_ce0;
reg    psosc_p_x2_we0;
reg   [31:0] psosc_p_x2_d0;
wire   [31:0] psosc_p_x2_q0;
reg   [1:0] psosc_p_v1_address0;
reg    psosc_p_v1_ce0;
reg    psosc_p_v1_we0;
reg   [31:0] psosc_p_v1_d0;
wire   [31:0] psosc_p_v1_q0;
reg   [1:0] psosc_p_v2_address0;
reg    psosc_p_v2_ce0;
reg    psosc_p_v2_we0;
reg   [31:0] psosc_p_v2_d0;
wire   [31:0] psosc_p_v2_q0;
reg   [1:0] psosc_p_x1_best_address0;
reg    psosc_p_x1_best_ce0;
reg    psosc_p_x1_best_we0;
reg   [31:0] psosc_p_x1_best_d0;
wire   [31:0] psosc_p_x1_best_q0;
reg   [1:0] psosc_p_x2_best_address0;
reg    psosc_p_x2_best_ce0;
reg    psosc_p_x2_best_we0;
reg   [31:0] psosc_p_x2_best_d0;
wire   [31:0] psosc_p_x2_best_q0;
wire   [0:0] psosc_ssdm_thread_load_fu_266_p1;
wire   [1:0] ap_CS_fsm;
wire   [31:0] grp_psosc_Execute_fu_130_finalx1;
wire    grp_psosc_Execute_fu_130_finalx1_ap_vld;
wire   [31:0] grp_psosc_Execute_fu_130_finalx2;
wire    grp_psosc_Execute_fu_130_finalx2_ap_vld;
wire    grp_psosc_Execute_fu_130_complete;
wire    grp_psosc_Execute_fu_130_complete_ap_vld;
wire    grp_psosc_Execute_fu_130_psosc_setupDone;
wire    grp_psosc_Execute_fu_130_psosc_calculationDone_i;
wire    grp_psosc_Execute_fu_130_psosc_calculationDone_o;
wire    grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld;
wire    grp_psosc_Execute_fu_130_psosc_negFormula;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_iterations;
wire    grp_psosc_Execute_fu_130_psosc_iterations_ap_vld;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_x1_global_o;
wire    grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_x2_global_o;
wire    grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_x1_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_x1_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_x1_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_x1_d0;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_x2_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_x2_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_x2_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_x2_d0;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_v1_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_v1_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_v1_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_v1_d0;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_v2_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_v2_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_v2_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_v2_d0;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_x1_best_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_x1_best_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_x1_best_d0;
wire   [1:0] grp_psosc_Execute_fu_130_psosc_p_x2_best_address0;
wire    grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0;
wire    grp_psosc_Execute_fu_130_psosc_p_x2_best_we0;
wire   [31:0] grp_psosc_Execute_fu_130_psosc_p_x2_best_d0;
wire    grp_psosc_Setup_fu_210_complete;
wire    grp_psosc_Setup_fu_210_complete_ap_vld;
wire    grp_psosc_Setup_fu_210_psosc_setupDone_i;
wire    grp_psosc_Setup_fu_210_psosc_setupDone_o;
wire    grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld;
wire    grp_psosc_Setup_fu_210_psosc_negFormula;
wire    grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_c1_cog;
wire    grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_c2_soc;
wire    grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_w;
wire    grp_psosc_Setup_fu_210_psosc_w_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_ax;
wire    grp_psosc_Setup_fu_210_psosc_ax_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_av;
wire    grp_psosc_Setup_fu_210_psosc_av_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_x1_global;
wire    grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_x2_global;
wire    grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_x1_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_x1_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_x1_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_x1_d0;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_x2_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_x2_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_x2_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_x2_d0;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_v1_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_v1_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_v1_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_v1_d0;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_v2_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_v2_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_v2_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_v2_d0;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_x1_best_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_x1_best_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_x1_best_d0;
wire   [1:0] grp_psosc_Setup_fu_210_psosc_p_x2_best_address0;
wire    grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0;
wire    grp_psosc_Setup_fu_210_psosc_p_x2_best_we0;
wire   [31:0] grp_psosc_Setup_fu_210_psosc_p_x2_best_d0;
wire    ap_CS_fsm_state2;
reg   [0:0] psosc_setupDone;
reg   [0:0] psosc_calculationDone;
reg   [0:0] psosc_negFormula;
reg   [31:0] psosc_w;
reg   [31:0] psosc_x1_global;
reg   [31:0] psosc_x2_global;

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_x1_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_x1_address0),
    .ce0(psosc_p_x1_ce0),
    .we0(psosc_p_x1_we0),
    .d0(psosc_p_x1_d0),
    .q0(psosc_p_x1_q0)
);

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_x2_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_x2_address0),
    .ce0(psosc_p_x2_ce0),
    .we0(psosc_p_x2_we0),
    .d0(psosc_p_x2_d0),
    .q0(psosc_p_x2_q0)
);

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_v1_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_v1_address0),
    .ce0(psosc_p_v1_ce0),
    .we0(psosc_p_v1_we0),
    .d0(psosc_p_v1_d0),
    .q0(psosc_p_v1_q0)
);

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_v2_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_v2_address0),
    .ce0(psosc_p_v2_ce0),
    .we0(psosc_p_v2_we0),
    .d0(psosc_p_v2_d0),
    .q0(psosc_p_v2_q0)
);

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_x1_best_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_x1_best_address0),
    .ce0(psosc_p_x1_best_ce0),
    .we0(psosc_p_x1_best_we0),
    .d0(psosc_p_x1_best_d0),
    .q0(psosc_p_x1_best_q0)
);

psosc_psosc_p_x1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
psosc_p_x2_best_U(
    .clk(clk),
    .reset(reset),
    .address0(psosc_p_x2_best_address0),
    .ce0(psosc_p_x2_best_ce0),
    .we0(psosc_p_x2_best_we0),
    .d0(psosc_p_x2_best_d0),
    .q0(psosc_p_x2_best_q0)
);

psosc_Execute grp_psosc_Execute_fu_130(
    .ap_clk(clk),
    .ap_rst(reset),
    .start(start),
    .c1(c1),
    .c2(c2),
    .finalx1(grp_psosc_Execute_fu_130_finalx1),
    .finalx1_ap_vld(grp_psosc_Execute_fu_130_finalx1_ap_vld),
    .finalx2(grp_psosc_Execute_fu_130_finalx2),
    .finalx2_ap_vld(grp_psosc_Execute_fu_130_finalx2_ap_vld),
    .complete(grp_psosc_Execute_fu_130_complete),
    .complete_ap_vld(grp_psosc_Execute_fu_130_complete_ap_vld),
    .psosc_setupDone(grp_psosc_Execute_fu_130_psosc_setupDone),
    .psosc_calculationDone_i(grp_psosc_Execute_fu_130_psosc_calculationDone_i),
    .psosc_calculationDone_o(grp_psosc_Execute_fu_130_psosc_calculationDone_o),
    .psosc_calculationDone_o_ap_vld(grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld),
    .psosc_negFormula(grp_psosc_Execute_fu_130_psosc_negFormula),
    .psosc_w(psosc_w),
    .psosc_iterations(grp_psosc_Execute_fu_130_psosc_iterations),
    .psosc_iterations_ap_vld(grp_psosc_Execute_fu_130_psosc_iterations_ap_vld),
    .psosc_x1_global_i(psosc_x1_global),
    .psosc_x1_global_o(grp_psosc_Execute_fu_130_psosc_x1_global_o),
    .psosc_x1_global_o_ap_vld(grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld),
    .psosc_x2_global_i(psosc_x2_global),
    .psosc_x2_global_o(grp_psosc_Execute_fu_130_psosc_x2_global_o),
    .psosc_x2_global_o_ap_vld(grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld),
    .psosc_p_x1_address0(grp_psosc_Execute_fu_130_psosc_p_x1_address0),
    .psosc_p_x1_ce0(grp_psosc_Execute_fu_130_psosc_p_x1_ce0),
    .psosc_p_x1_we0(grp_psosc_Execute_fu_130_psosc_p_x1_we0),
    .psosc_p_x1_d0(grp_psosc_Execute_fu_130_psosc_p_x1_d0),
    .psosc_p_x1_q0(psosc_p_x1_q0),
    .psosc_p_x2_address0(grp_psosc_Execute_fu_130_psosc_p_x2_address0),
    .psosc_p_x2_ce0(grp_psosc_Execute_fu_130_psosc_p_x2_ce0),
    .psosc_p_x2_we0(grp_psosc_Execute_fu_130_psosc_p_x2_we0),
    .psosc_p_x2_d0(grp_psosc_Execute_fu_130_psosc_p_x2_d0),
    .psosc_p_x2_q0(psosc_p_x2_q0),
    .psosc_p_v1_address0(grp_psosc_Execute_fu_130_psosc_p_v1_address0),
    .psosc_p_v1_ce0(grp_psosc_Execute_fu_130_psosc_p_v1_ce0),
    .psosc_p_v1_we0(grp_psosc_Execute_fu_130_psosc_p_v1_we0),
    .psosc_p_v1_d0(grp_psosc_Execute_fu_130_psosc_p_v1_d0),
    .psosc_p_v1_q0(psosc_p_v1_q0),
    .psosc_p_v2_address0(grp_psosc_Execute_fu_130_psosc_p_v2_address0),
    .psosc_p_v2_ce0(grp_psosc_Execute_fu_130_psosc_p_v2_ce0),
    .psosc_p_v2_we0(grp_psosc_Execute_fu_130_psosc_p_v2_we0),
    .psosc_p_v2_d0(grp_psosc_Execute_fu_130_psosc_p_v2_d0),
    .psosc_p_v2_q0(psosc_p_v2_q0),
    .psosc_p_x1_best_address0(grp_psosc_Execute_fu_130_psosc_p_x1_best_address0),
    .psosc_p_x1_best_ce0(grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0),
    .psosc_p_x1_best_we0(grp_psosc_Execute_fu_130_psosc_p_x1_best_we0),
    .psosc_p_x1_best_d0(grp_psosc_Execute_fu_130_psosc_p_x1_best_d0),
    .psosc_p_x1_best_q0(psosc_p_x1_best_q0),
    .psosc_p_x2_best_address0(grp_psosc_Execute_fu_130_psosc_p_x2_best_address0),
    .psosc_p_x2_best_ce0(grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0),
    .psosc_p_x2_best_we0(grp_psosc_Execute_fu_130_psosc_p_x2_best_we0),
    .psosc_p_x2_best_d0(grp_psosc_Execute_fu_130_psosc_p_x2_best_d0),
    .psosc_p_x2_best_q0(psosc_p_x2_best_q0)
);

psosc_Setup grp_psosc_Setup_fu_210(
    .ap_clk(clk),
    .ap_rst(reset),
    .start(start),
    .negativeFormula(negativeFormula),
    .c1(c1),
    .c2(c2),
    .complete(grp_psosc_Setup_fu_210_complete),
    .complete_ap_vld(grp_psosc_Setup_fu_210_complete_ap_vld),
    .psosc_setupDone_i(grp_psosc_Setup_fu_210_psosc_setupDone_i),
    .psosc_setupDone_o(grp_psosc_Setup_fu_210_psosc_setupDone_o),
    .psosc_setupDone_o_ap_vld(grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld),
    .psosc_negFormula(grp_psosc_Setup_fu_210_psosc_negFormula),
    .psosc_negFormula_ap_vld(grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld),
    .psosc_c1_cog(grp_psosc_Setup_fu_210_psosc_c1_cog),
    .psosc_c1_cog_ap_vld(grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld),
    .psosc_c2_soc(grp_psosc_Setup_fu_210_psosc_c2_soc),
    .psosc_c2_soc_ap_vld(grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld),
    .psosc_w(grp_psosc_Setup_fu_210_psosc_w),
    .psosc_w_ap_vld(grp_psosc_Setup_fu_210_psosc_w_ap_vld),
    .psosc_ax(grp_psosc_Setup_fu_210_psosc_ax),
    .psosc_ax_ap_vld(grp_psosc_Setup_fu_210_psosc_ax_ap_vld),
    .psosc_av(grp_psosc_Setup_fu_210_psosc_av),
    .psosc_av_ap_vld(grp_psosc_Setup_fu_210_psosc_av_ap_vld),
    .psosc_x1_global(grp_psosc_Setup_fu_210_psosc_x1_global),
    .psosc_x1_global_ap_vld(grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld),
    .psosc_x2_global(grp_psosc_Setup_fu_210_psosc_x2_global),
    .psosc_x2_global_ap_vld(grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld),
    .psosc_p_x1_address0(grp_psosc_Setup_fu_210_psosc_p_x1_address0),
    .psosc_p_x1_ce0(grp_psosc_Setup_fu_210_psosc_p_x1_ce0),
    .psosc_p_x1_we0(grp_psosc_Setup_fu_210_psosc_p_x1_we0),
    .psosc_p_x1_d0(grp_psosc_Setup_fu_210_psosc_p_x1_d0),
    .psosc_p_x2_address0(grp_psosc_Setup_fu_210_psosc_p_x2_address0),
    .psosc_p_x2_ce0(grp_psosc_Setup_fu_210_psosc_p_x2_ce0),
    .psosc_p_x2_we0(grp_psosc_Setup_fu_210_psosc_p_x2_we0),
    .psosc_p_x2_d0(grp_psosc_Setup_fu_210_psosc_p_x2_d0),
    .psosc_p_v1_address0(grp_psosc_Setup_fu_210_psosc_p_v1_address0),
    .psosc_p_v1_ce0(grp_psosc_Setup_fu_210_psosc_p_v1_ce0),
    .psosc_p_v1_we0(grp_psosc_Setup_fu_210_psosc_p_v1_we0),
    .psosc_p_v1_d0(grp_psosc_Setup_fu_210_psosc_p_v1_d0),
    .psosc_p_v2_address0(grp_psosc_Setup_fu_210_psosc_p_v2_address0),
    .psosc_p_v2_ce0(grp_psosc_Setup_fu_210_psosc_p_v2_ce0),
    .psosc_p_v2_we0(grp_psosc_Setup_fu_210_psosc_p_v2_we0),
    .psosc_p_v2_d0(grp_psosc_Setup_fu_210_psosc_p_v2_d0),
    .psosc_p_x1_best_address0(grp_psosc_Setup_fu_210_psosc_p_x1_best_address0),
    .psosc_p_x1_best_ce0(grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0),
    .psosc_p_x1_best_we0(grp_psosc_Setup_fu_210_psosc_p_x1_best_we0),
    .psosc_p_x1_best_d0(grp_psosc_Setup_fu_210_psosc_p_x1_best_d0),
    .psosc_p_x2_best_address0(grp_psosc_Setup_fu_210_psosc_p_x2_best_address0),
    .psosc_p_x2_best_ce0(grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0),
    .psosc_p_x2_best_we0(grp_psosc_Setup_fu_210_psosc_p_x2_best_we0),
    .psosc_p_x2_best_d0(grp_psosc_Setup_fu_210_psosc_p_x2_best_d0)
);

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_complete_ap_vld)) begin
        complete <= grp_psosc_Setup_fu_210_complete;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_complete_ap_vld)) begin
        complete <= grp_psosc_Execute_fu_130_complete;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Execute_fu_130_finalx1_ap_vld)) begin
        finalx1 <= grp_psosc_Execute_fu_130_finalx1;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Execute_fu_130_finalx2_ap_vld)) begin
        finalx2 <= grp_psosc_Execute_fu_130_finalx2;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld)) begin
        psosc_calculationDone <= grp_psosc_Execute_fu_130_psosc_calculationDone_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld)) begin
        psosc_negFormula <= grp_psosc_Setup_fu_210_psosc_negFormula;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld)) begin
        psosc_setupDone <= grp_psosc_Setup_fu_210_psosc_setupDone_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_w_ap_vld)) begin
        psosc_w <= grp_psosc_Setup_fu_210_psosc_w;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld)) begin
        psosc_x1_global <= grp_psosc_Setup_fu_210_psosc_x1_global;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld)) begin
        psosc_x1_global <= grp_psosc_Execute_fu_130_psosc_x1_global_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld)) begin
        psosc_x2_global <= grp_psosc_Setup_fu_210_psosc_x2_global;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld)) begin
        psosc_x2_global <= grp_psosc_Execute_fu_130_psosc_x2_global_o;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) begin
        psosc_p_v1_address0 = grp_psosc_Setup_fu_210_psosc_p_v1_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) begin
        psosc_p_v1_address0 = grp_psosc_Execute_fu_130_psosc_p_v1_address0;
    end else begin
        psosc_p_v1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) begin
        psosc_p_v1_ce0 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) begin
        psosc_p_v1_ce0 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0;
    end else begin
        psosc_p_v1_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) begin
        psosc_p_v1_d0 = grp_psosc_Setup_fu_210_psosc_p_v1_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) begin
        psosc_p_v1_d0 = grp_psosc_Execute_fu_130_psosc_p_v1_d0;
    end else begin
        psosc_p_v1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v1_ce0)) begin
        psosc_p_v1_we0 = grp_psosc_Setup_fu_210_psosc_p_v1_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v1_ce0)) begin
        psosc_p_v1_we0 = grp_psosc_Execute_fu_130_psosc_p_v1_we0;
    end else begin
        psosc_p_v1_we0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) begin
        psosc_p_v2_address0 = grp_psosc_Setup_fu_210_psosc_p_v2_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) begin
        psosc_p_v2_address0 = grp_psosc_Execute_fu_130_psosc_p_v2_address0;
    end else begin
        psosc_p_v2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) begin
        psosc_p_v2_ce0 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) begin
        psosc_p_v2_ce0 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0;
    end else begin
        psosc_p_v2_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) begin
        psosc_p_v2_d0 = grp_psosc_Setup_fu_210_psosc_p_v2_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) begin
        psosc_p_v2_d0 = grp_psosc_Execute_fu_130_psosc_p_v2_d0;
    end else begin
        psosc_p_v2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_v2_ce0)) begin
        psosc_p_v2_we0 = grp_psosc_Setup_fu_210_psosc_p_v2_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_v2_ce0)) begin
        psosc_p_v2_we0 = grp_psosc_Execute_fu_130_psosc_p_v2_we0;
    end else begin
        psosc_p_v2_we0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) begin
        psosc_p_x1_address0 = grp_psosc_Setup_fu_210_psosc_p_x1_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) begin
        psosc_p_x1_address0 = grp_psosc_Execute_fu_130_psosc_p_x1_address0;
    end else begin
        psosc_p_x1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_address0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_address0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_address0;
    end else begin
        psosc_p_x1_best_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_ce0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_ce0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0;
    end else begin
        psosc_p_x1_best_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_d0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_d0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_d0;
    end else begin
        psosc_p_x1_best_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_we0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0)) begin
        psosc_p_x1_best_we0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_we0;
    end else begin
        psosc_p_x1_best_we0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) begin
        psosc_p_x1_ce0 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) begin
        psosc_p_x1_ce0 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0;
    end else begin
        psosc_p_x1_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) begin
        psosc_p_x1_d0 = grp_psosc_Setup_fu_210_psosc_p_x1_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) begin
        psosc_p_x1_d0 = grp_psosc_Execute_fu_130_psosc_p_x1_d0;
    end else begin
        psosc_p_x1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x1_ce0)) begin
        psosc_p_x1_we0 = grp_psosc_Setup_fu_210_psosc_p_x1_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x1_ce0)) begin
        psosc_p_x1_we0 = grp_psosc_Execute_fu_130_psosc_p_x1_we0;
    end else begin
        psosc_p_x1_we0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) begin
        psosc_p_x2_address0 = grp_psosc_Setup_fu_210_psosc_p_x2_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) begin
        psosc_p_x2_address0 = grp_psosc_Execute_fu_130_psosc_p_x2_address0;
    end else begin
        psosc_p_x2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_address0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_address0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_address0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_address0;
    end else begin
        psosc_p_x2_best_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_ce0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_ce0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0;
    end else begin
        psosc_p_x2_best_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_d0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_d0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_d0;
    end else begin
        psosc_p_x2_best_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_we0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0)) begin
        psosc_p_x2_best_we0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_we0;
    end else begin
        psosc_p_x2_best_we0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) begin
        psosc_p_x2_ce0 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) begin
        psosc_p_x2_ce0 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0;
    end else begin
        psosc_p_x2_ce0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) begin
        psosc_p_x2_d0 = grp_psosc_Setup_fu_210_psosc_p_x2_d0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) begin
        psosc_p_x2_d0 = grp_psosc_Execute_fu_130_psosc_p_x2_d0;
    end else begin
        psosc_p_x2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_psosc_Setup_fu_210_psosc_p_x2_ce0)) begin
        psosc_p_x2_we0 = grp_psosc_Setup_fu_210_psosc_p_x2_we0;
    end else if ((1'b1 == grp_psosc_Execute_fu_130_psosc_p_x2_ce0)) begin
        psosc_p_x2_we0 = grp_psosc_Execute_fu_130_psosc_p_x2_we0;
    end else begin
        psosc_p_x2_we0 = 'bx;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_psosc_Execute_fu_130_psosc_calculationDone_i = psosc_calculationDone;

assign grp_psosc_Execute_fu_130_psosc_negFormula = psosc_negFormula;

assign grp_psosc_Execute_fu_130_psosc_setupDone = psosc_setupDone;

assign grp_psosc_Setup_fu_210_psosc_setupDone_i = psosc_setupDone;

assign psosc_ssdm_thread_load_fu_266_p1 = 1'd0;

endmodule //psosc
