// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="floatPrototypec,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.702000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=179,HLS_SYN_LUT=348}" *)

module floatPrototypec (
        clk,
        reset,
        float1,
        float2,
        float3
);


input   clk;
input   reset;
input  [31:0] float1;
input  [31:0] float2;
output  [31:0] float3;

reg[31:0] float3;

wire   [0:0] floatPrototypec_s_load_fu_74_p1;
wire   [1:0] ap_CS_fsm;
wire   [31:0] grp_floatPrototypec_multiply_fu_60_float3;
wire    grp_floatPrototypec_multiply_fu_60_float3_ap_vld;
wire    ap_CS_fsm_state2;

floatPrototypec_multiply grp_floatPrototypec_multiply_fu_60(
    .ap_clk(clk),
    .ap_rst(reset),
    .float1(float1),
    .float2(float2),
    .float3(grp_floatPrototypec_multiply_fu_60_float3),
    .float3_ap_vld(grp_floatPrototypec_multiply_fu_60_float3_ap_vld)
);

always @ (posedge clk) begin
    if ((1'b1 == grp_floatPrototypec_multiply_fu_60_float3_ap_vld)) begin
        float3 <= grp_floatPrototypec_multiply_fu_60_float3;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign floatPrototypec_s_load_fu_74_p1 = 1'd0;

endmodule //floatPrototypec
