// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfloatprototypec.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFloatprototypec_CfgInitialize(XFloatprototypec *InstancePtr, XFloatprototypec_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFloatprototypec_SetFloat1(XFloatprototypec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFloatprototypec_WriteReg(InstancePtr->Slv0_BaseAddress, XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT1_DATA, Data);
}

u32 XFloatprototypec_GetFloat1(XFloatprototypec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFloatprototypec_ReadReg(InstancePtr->Slv0_BaseAddress, XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT1_DATA);
    return Data;
}

void XFloatprototypec_SetFloat2(XFloatprototypec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFloatprototypec_WriteReg(InstancePtr->Slv0_BaseAddress, XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT2_DATA, Data);
}

u32 XFloatprototypec_GetFloat2(XFloatprototypec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFloatprototypec_ReadReg(InstancePtr->Slv0_BaseAddress, XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT2_DATA);
    return Data;
}

u32 XFloatprototypec_GetFloat3(XFloatprototypec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFloatprototypec_ReadReg(InstancePtr->Slv0_BaseAddress, XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT3_DATA);
    return Data;
}

