// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// slv0
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : reserved
// 0x14 : Data signal of float1
//        bit 31~0 - float1[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of float2
//        bit 31~0 - float2[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of float3
//        bit 31~0 - float3[31:0] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT1_DATA 0x14
#define XFLOATPROTOTYPEC_SLV0_BITS_FLOAT1_DATA 32
#define XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT2_DATA 0x1c
#define XFLOATPROTOTYPEC_SLV0_BITS_FLOAT2_DATA 32
#define XFLOATPROTOTYPEC_SLV0_ADDR_FLOAT3_DATA 0x24
#define XFLOATPROTOTYPEC_SLV0_BITS_FLOAT3_DATA 32

