// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfloatprototypec.h"

extern XFloatprototypec_Config XFloatprototypec_ConfigTable[];

XFloatprototypec_Config *XFloatprototypec_LookupConfig(u16 DeviceId) {
	XFloatprototypec_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFLOATPROTOTYPEC_NUM_INSTANCES; Index++) {
		if (XFloatprototypec_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFloatprototypec_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFloatprototypec_Initialize(XFloatprototypec *InstancePtr, u16 DeviceId) {
	XFloatprototypec_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFloatprototypec_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFloatprototypec_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

