// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _psosc_HH_
#define _psosc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "psosc_Execute.h"
#include "psosc_Setup.h"
#include "psosc_psosc_p_x1.h"

namespace ap_rtl {

struct psosc : public sc_module {
    // Port declarations 9
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_in< sc_logic > start;
    sc_in< sc_logic > negativeFormula;
    sc_in< sc_lv<32> > c1;
    sc_in< sc_lv<32> > c2;
    sc_out< sc_lv<32> > finalx1;
    sc_out< sc_lv<32> > finalx2;
    sc_out< sc_logic > complete;


    // Module declarations
    psosc(sc_module_name name);
    SC_HAS_PROCESS(psosc);

    ~psosc();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    psosc_psosc_p_x1* psosc_p_x1_U;
    psosc_psosc_p_x1* psosc_p_x2_U;
    psosc_psosc_p_x1* psosc_p_v1_U;
    psosc_psosc_p_x1* psosc_p_v2_U;
    psosc_psosc_p_x1* psosc_p_x1_best_U;
    psosc_psosc_p_x1* psosc_p_x2_best_U;
    psosc_Execute* grp_psosc_Execute_fu_130;
    psosc_Setup* grp_psosc_Setup_fu_210;
    sc_signal< sc_lv<2> > psosc_p_x1_address0;
    sc_signal< sc_logic > psosc_p_x1_ce0;
    sc_signal< sc_logic > psosc_p_x1_we0;
    sc_signal< sc_lv<32> > psosc_p_x1_d0;
    sc_signal< sc_lv<32> > psosc_p_x1_q0;
    sc_signal< sc_lv<2> > psosc_p_x2_address0;
    sc_signal< sc_logic > psosc_p_x2_ce0;
    sc_signal< sc_logic > psosc_p_x2_we0;
    sc_signal< sc_lv<32> > psosc_p_x2_d0;
    sc_signal< sc_lv<32> > psosc_p_x2_q0;
    sc_signal< sc_lv<2> > psosc_p_v1_address0;
    sc_signal< sc_logic > psosc_p_v1_ce0;
    sc_signal< sc_logic > psosc_p_v1_we0;
    sc_signal< sc_lv<32> > psosc_p_v1_d0;
    sc_signal< sc_lv<32> > psosc_p_v1_q0;
    sc_signal< sc_lv<2> > psosc_p_v2_address0;
    sc_signal< sc_logic > psosc_p_v2_ce0;
    sc_signal< sc_logic > psosc_p_v2_we0;
    sc_signal< sc_lv<32> > psosc_p_v2_d0;
    sc_signal< sc_lv<32> > psosc_p_v2_q0;
    sc_signal< sc_lv<2> > psosc_p_x1_best_address0;
    sc_signal< sc_logic > psosc_p_x1_best_ce0;
    sc_signal< sc_logic > psosc_p_x1_best_we0;
    sc_signal< sc_lv<32> > psosc_p_x1_best_d0;
    sc_signal< sc_lv<32> > psosc_p_x1_best_q0;
    sc_signal< sc_lv<2> > psosc_p_x2_best_address0;
    sc_signal< sc_logic > psosc_p_x2_best_ce0;
    sc_signal< sc_logic > psosc_p_x2_best_we0;
    sc_signal< sc_lv<32> > psosc_p_x2_best_d0;
    sc_signal< sc_lv<32> > psosc_p_x2_best_q0;
    sc_signal< sc_lv<1> > psosc_ssdm_thread_load_fu_266_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_finalx1;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_finalx1_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_finalx2;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_finalx2_ap_vld;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_complete;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_complete_ap_vld;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_setupDone;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_calculationDone_i;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_calculationDone_o;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_negFormula;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_iterations;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_iterations_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_x1_global_o;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_x2_global_o;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_x1_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x1_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x1_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_x1_d0;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_x2_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x2_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x2_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_x2_d0;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_v1_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_v1_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_v1_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_v1_d0;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_v2_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_v2_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_v2_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_v2_d0;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_x1_best_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x1_best_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_x1_best_d0;
    sc_signal< sc_lv<2> > grp_psosc_Execute_fu_130_psosc_p_x2_best_address0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0;
    sc_signal< sc_logic > grp_psosc_Execute_fu_130_psosc_p_x2_best_we0;
    sc_signal< sc_lv<32> > grp_psosc_Execute_fu_130_psosc_p_x2_best_d0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_complete;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_complete_ap_vld;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_setupDone_i;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_setupDone_o;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_negFormula;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_c1_cog;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_c2_soc;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_w;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_w_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_ax;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_ax_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_av;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_av_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_x1_global;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_x2_global;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_x1_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x1_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x1_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_x1_d0;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_x2_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x2_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x2_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_x2_d0;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_v1_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_v1_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_v1_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_v1_d0;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_v2_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_v2_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_v2_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_v2_d0;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_x1_best_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x1_best_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_x1_best_d0;
    sc_signal< sc_lv<2> > grp_psosc_Setup_fu_210_psosc_p_x2_best_address0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0;
    sc_signal< sc_logic > grp_psosc_Setup_fu_210_psosc_p_x2_best_we0;
    sc_signal< sc_lv<32> > grp_psosc_Setup_fu_210_psosc_p_x2_best_d0;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > psosc_setupDone;
    sc_signal< sc_lv<1> > psosc_calculationDone;
    sc_signal< sc_lv<1> > psosc_negFormula;
    sc_signal< sc_lv<32> > psosc_w;
    sc_signal< sc_lv<32> > psosc_x1_global;
    sc_signal< sc_lv<32> > psosc_x2_global;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_complete();
    void thread_finalx1();
    void thread_finalx2();
    void thread_psosc_calculationDone();
    void thread_psosc_negFormula();
    void thread_psosc_setupDone();
    void thread_psosc_w();
    void thread_psosc_x1_global();
    void thread_psosc_x2_global();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_grp_psosc_Execute_fu_130_psosc_calculationDone_i();
    void thread_grp_psosc_Execute_fu_130_psosc_negFormula();
    void thread_grp_psosc_Execute_fu_130_psosc_setupDone();
    void thread_grp_psosc_Setup_fu_210_psosc_setupDone_i();
    void thread_psosc_p_v1_address0();
    void thread_psosc_p_v1_ce0();
    void thread_psosc_p_v1_d0();
    void thread_psosc_p_v1_we0();
    void thread_psosc_p_v2_address0();
    void thread_psosc_p_v2_ce0();
    void thread_psosc_p_v2_d0();
    void thread_psosc_p_v2_we0();
    void thread_psosc_p_x1_address0();
    void thread_psosc_p_x1_best_address0();
    void thread_psosc_p_x1_best_ce0();
    void thread_psosc_p_x1_best_d0();
    void thread_psosc_p_x1_best_we0();
    void thread_psosc_p_x1_ce0();
    void thread_psosc_p_x1_d0();
    void thread_psosc_p_x1_we0();
    void thread_psosc_p_x2_address0();
    void thread_psosc_p_x2_best_address0();
    void thread_psosc_p_x2_best_ce0();
    void thread_psosc_p_x2_best_d0();
    void thread_psosc_p_x2_best_we0();
    void thread_psosc_p_x2_ce0();
    void thread_psosc_p_x2_d0();
    void thread_psosc_p_x2_we0();
    void thread_psosc_ssdm_thread_load_fu_266_p1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
