// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "psosc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic psosc::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> psosc::ap_const_lv1_0 = "0";
const sc_lv<32> psosc::ap_const_lv32_1 = "1";
const sc_lv<1> psosc::ap_const_lv1_1 = "1";
const sc_lv<2> psosc::ap_const_lv2_0 = "00";
const sc_logic psosc::ap_const_logic_0 = sc_dt::Log_0;
const bool psosc::ap_const_boolean_1 = true;

psosc::psosc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    psosc_p_x1_U = new psosc_psosc_p_x1("psosc_p_x1_U");
    psosc_p_x1_U->clk(clk);
    psosc_p_x1_U->reset(reset);
    psosc_p_x1_U->address0(psosc_p_x1_address0);
    psosc_p_x1_U->ce0(psosc_p_x1_ce0);
    psosc_p_x1_U->we0(psosc_p_x1_we0);
    psosc_p_x1_U->d0(psosc_p_x1_d0);
    psosc_p_x1_U->q0(psosc_p_x1_q0);
    psosc_p_x2_U = new psosc_psosc_p_x1("psosc_p_x2_U");
    psosc_p_x2_U->clk(clk);
    psosc_p_x2_U->reset(reset);
    psosc_p_x2_U->address0(psosc_p_x2_address0);
    psosc_p_x2_U->ce0(psosc_p_x2_ce0);
    psosc_p_x2_U->we0(psosc_p_x2_we0);
    psosc_p_x2_U->d0(psosc_p_x2_d0);
    psosc_p_x2_U->q0(psosc_p_x2_q0);
    psosc_p_v1_U = new psosc_psosc_p_x1("psosc_p_v1_U");
    psosc_p_v1_U->clk(clk);
    psosc_p_v1_U->reset(reset);
    psosc_p_v1_U->address0(psosc_p_v1_address0);
    psosc_p_v1_U->ce0(psosc_p_v1_ce0);
    psosc_p_v1_U->we0(psosc_p_v1_we0);
    psosc_p_v1_U->d0(psosc_p_v1_d0);
    psosc_p_v1_U->q0(psosc_p_v1_q0);
    psosc_p_v2_U = new psosc_psosc_p_x1("psosc_p_v2_U");
    psosc_p_v2_U->clk(clk);
    psosc_p_v2_U->reset(reset);
    psosc_p_v2_U->address0(psosc_p_v2_address0);
    psosc_p_v2_U->ce0(psosc_p_v2_ce0);
    psosc_p_v2_U->we0(psosc_p_v2_we0);
    psosc_p_v2_U->d0(psosc_p_v2_d0);
    psosc_p_v2_U->q0(psosc_p_v2_q0);
    psosc_p_x1_best_U = new psosc_psosc_p_x1("psosc_p_x1_best_U");
    psosc_p_x1_best_U->clk(clk);
    psosc_p_x1_best_U->reset(reset);
    psosc_p_x1_best_U->address0(psosc_p_x1_best_address0);
    psosc_p_x1_best_U->ce0(psosc_p_x1_best_ce0);
    psosc_p_x1_best_U->we0(psosc_p_x1_best_we0);
    psosc_p_x1_best_U->d0(psosc_p_x1_best_d0);
    psosc_p_x1_best_U->q0(psosc_p_x1_best_q0);
    psosc_p_x2_best_U = new psosc_psosc_p_x1("psosc_p_x2_best_U");
    psosc_p_x2_best_U->clk(clk);
    psosc_p_x2_best_U->reset(reset);
    psosc_p_x2_best_U->address0(psosc_p_x2_best_address0);
    psosc_p_x2_best_U->ce0(psosc_p_x2_best_ce0);
    psosc_p_x2_best_U->we0(psosc_p_x2_best_we0);
    psosc_p_x2_best_U->d0(psosc_p_x2_best_d0);
    psosc_p_x2_best_U->q0(psosc_p_x2_best_q0);
    grp_psosc_Execute_fu_130 = new psosc_Execute("grp_psosc_Execute_fu_130");
    grp_psosc_Execute_fu_130->ap_clk(clk);
    grp_psosc_Execute_fu_130->ap_rst(reset);
    grp_psosc_Execute_fu_130->start(start);
    grp_psosc_Execute_fu_130->c1(c1);
    grp_psosc_Execute_fu_130->c2(c2);
    grp_psosc_Execute_fu_130->finalx1(grp_psosc_Execute_fu_130_finalx1);
    grp_psosc_Execute_fu_130->finalx1_ap_vld(grp_psosc_Execute_fu_130_finalx1_ap_vld);
    grp_psosc_Execute_fu_130->finalx2(grp_psosc_Execute_fu_130_finalx2);
    grp_psosc_Execute_fu_130->finalx2_ap_vld(grp_psosc_Execute_fu_130_finalx2_ap_vld);
    grp_psosc_Execute_fu_130->complete(grp_psosc_Execute_fu_130_complete);
    grp_psosc_Execute_fu_130->complete_ap_vld(grp_psosc_Execute_fu_130_complete_ap_vld);
    grp_psosc_Execute_fu_130->psosc_setupDone(grp_psosc_Execute_fu_130_psosc_setupDone);
    grp_psosc_Execute_fu_130->psosc_calculationDone_i(grp_psosc_Execute_fu_130_psosc_calculationDone_i);
    grp_psosc_Execute_fu_130->psosc_calculationDone_o(grp_psosc_Execute_fu_130_psosc_calculationDone_o);
    grp_psosc_Execute_fu_130->psosc_calculationDone_o_ap_vld(grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld);
    grp_psosc_Execute_fu_130->psosc_negFormula(grp_psosc_Execute_fu_130_psosc_negFormula);
    grp_psosc_Execute_fu_130->psosc_w(psosc_w);
    grp_psosc_Execute_fu_130->psosc_iterations(grp_psosc_Execute_fu_130_psosc_iterations);
    grp_psosc_Execute_fu_130->psosc_iterations_ap_vld(grp_psosc_Execute_fu_130_psosc_iterations_ap_vld);
    grp_psosc_Execute_fu_130->psosc_x1_global_i(psosc_x1_global);
    grp_psosc_Execute_fu_130->psosc_x1_global_o(grp_psosc_Execute_fu_130_psosc_x1_global_o);
    grp_psosc_Execute_fu_130->psosc_x1_global_o_ap_vld(grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld);
    grp_psosc_Execute_fu_130->psosc_x2_global_i(psosc_x2_global);
    grp_psosc_Execute_fu_130->psosc_x2_global_o(grp_psosc_Execute_fu_130_psosc_x2_global_o);
    grp_psosc_Execute_fu_130->psosc_x2_global_o_ap_vld(grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld);
    grp_psosc_Execute_fu_130->psosc_p_x1_address0(grp_psosc_Execute_fu_130_psosc_p_x1_address0);
    grp_psosc_Execute_fu_130->psosc_p_x1_ce0(grp_psosc_Execute_fu_130_psosc_p_x1_ce0);
    grp_psosc_Execute_fu_130->psosc_p_x1_we0(grp_psosc_Execute_fu_130_psosc_p_x1_we0);
    grp_psosc_Execute_fu_130->psosc_p_x1_d0(grp_psosc_Execute_fu_130_psosc_p_x1_d0);
    grp_psosc_Execute_fu_130->psosc_p_x1_q0(psosc_p_x1_q0);
    grp_psosc_Execute_fu_130->psosc_p_x2_address0(grp_psosc_Execute_fu_130_psosc_p_x2_address0);
    grp_psosc_Execute_fu_130->psosc_p_x2_ce0(grp_psosc_Execute_fu_130_psosc_p_x2_ce0);
    grp_psosc_Execute_fu_130->psosc_p_x2_we0(grp_psosc_Execute_fu_130_psosc_p_x2_we0);
    grp_psosc_Execute_fu_130->psosc_p_x2_d0(grp_psosc_Execute_fu_130_psosc_p_x2_d0);
    grp_psosc_Execute_fu_130->psosc_p_x2_q0(psosc_p_x2_q0);
    grp_psosc_Execute_fu_130->psosc_p_v1_address0(grp_psosc_Execute_fu_130_psosc_p_v1_address0);
    grp_psosc_Execute_fu_130->psosc_p_v1_ce0(grp_psosc_Execute_fu_130_psosc_p_v1_ce0);
    grp_psosc_Execute_fu_130->psosc_p_v1_we0(grp_psosc_Execute_fu_130_psosc_p_v1_we0);
    grp_psosc_Execute_fu_130->psosc_p_v1_d0(grp_psosc_Execute_fu_130_psosc_p_v1_d0);
    grp_psosc_Execute_fu_130->psosc_p_v1_q0(psosc_p_v1_q0);
    grp_psosc_Execute_fu_130->psosc_p_v2_address0(grp_psosc_Execute_fu_130_psosc_p_v2_address0);
    grp_psosc_Execute_fu_130->psosc_p_v2_ce0(grp_psosc_Execute_fu_130_psosc_p_v2_ce0);
    grp_psosc_Execute_fu_130->psosc_p_v2_we0(grp_psosc_Execute_fu_130_psosc_p_v2_we0);
    grp_psosc_Execute_fu_130->psosc_p_v2_d0(grp_psosc_Execute_fu_130_psosc_p_v2_d0);
    grp_psosc_Execute_fu_130->psosc_p_v2_q0(psosc_p_v2_q0);
    grp_psosc_Execute_fu_130->psosc_p_x1_best_address0(grp_psosc_Execute_fu_130_psosc_p_x1_best_address0);
    grp_psosc_Execute_fu_130->psosc_p_x1_best_ce0(grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0);
    grp_psosc_Execute_fu_130->psosc_p_x1_best_we0(grp_psosc_Execute_fu_130_psosc_p_x1_best_we0);
    grp_psosc_Execute_fu_130->psosc_p_x1_best_d0(grp_psosc_Execute_fu_130_psosc_p_x1_best_d0);
    grp_psosc_Execute_fu_130->psosc_p_x1_best_q0(psosc_p_x1_best_q0);
    grp_psosc_Execute_fu_130->psosc_p_x2_best_address0(grp_psosc_Execute_fu_130_psosc_p_x2_best_address0);
    grp_psosc_Execute_fu_130->psosc_p_x2_best_ce0(grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0);
    grp_psosc_Execute_fu_130->psosc_p_x2_best_we0(grp_psosc_Execute_fu_130_psosc_p_x2_best_we0);
    grp_psosc_Execute_fu_130->psosc_p_x2_best_d0(grp_psosc_Execute_fu_130_psosc_p_x2_best_d0);
    grp_psosc_Execute_fu_130->psosc_p_x2_best_q0(psosc_p_x2_best_q0);
    grp_psosc_Setup_fu_210 = new psosc_Setup("grp_psosc_Setup_fu_210");
    grp_psosc_Setup_fu_210->ap_clk(clk);
    grp_psosc_Setup_fu_210->ap_rst(reset);
    grp_psosc_Setup_fu_210->start(start);
    grp_psosc_Setup_fu_210->negativeFormula(negativeFormula);
    grp_psosc_Setup_fu_210->c1(c1);
    grp_psosc_Setup_fu_210->c2(c2);
    grp_psosc_Setup_fu_210->complete(grp_psosc_Setup_fu_210_complete);
    grp_psosc_Setup_fu_210->complete_ap_vld(grp_psosc_Setup_fu_210_complete_ap_vld);
    grp_psosc_Setup_fu_210->psosc_setupDone_i(grp_psosc_Setup_fu_210_psosc_setupDone_i);
    grp_psosc_Setup_fu_210->psosc_setupDone_o(grp_psosc_Setup_fu_210_psosc_setupDone_o);
    grp_psosc_Setup_fu_210->psosc_setupDone_o_ap_vld(grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld);
    grp_psosc_Setup_fu_210->psosc_negFormula(grp_psosc_Setup_fu_210_psosc_negFormula);
    grp_psosc_Setup_fu_210->psosc_negFormula_ap_vld(grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld);
    grp_psosc_Setup_fu_210->psosc_c1_cog(grp_psosc_Setup_fu_210_psosc_c1_cog);
    grp_psosc_Setup_fu_210->psosc_c1_cog_ap_vld(grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld);
    grp_psosc_Setup_fu_210->psosc_c2_soc(grp_psosc_Setup_fu_210_psosc_c2_soc);
    grp_psosc_Setup_fu_210->psosc_c2_soc_ap_vld(grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld);
    grp_psosc_Setup_fu_210->psosc_w(grp_psosc_Setup_fu_210_psosc_w);
    grp_psosc_Setup_fu_210->psosc_w_ap_vld(grp_psosc_Setup_fu_210_psosc_w_ap_vld);
    grp_psosc_Setup_fu_210->psosc_ax(grp_psosc_Setup_fu_210_psosc_ax);
    grp_psosc_Setup_fu_210->psosc_ax_ap_vld(grp_psosc_Setup_fu_210_psosc_ax_ap_vld);
    grp_psosc_Setup_fu_210->psosc_av(grp_psosc_Setup_fu_210_psosc_av);
    grp_psosc_Setup_fu_210->psosc_av_ap_vld(grp_psosc_Setup_fu_210_psosc_av_ap_vld);
    grp_psosc_Setup_fu_210->psosc_x1_global(grp_psosc_Setup_fu_210_psosc_x1_global);
    grp_psosc_Setup_fu_210->psosc_x1_global_ap_vld(grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld);
    grp_psosc_Setup_fu_210->psosc_x2_global(grp_psosc_Setup_fu_210_psosc_x2_global);
    grp_psosc_Setup_fu_210->psosc_x2_global_ap_vld(grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld);
    grp_psosc_Setup_fu_210->psosc_p_x1_address0(grp_psosc_Setup_fu_210_psosc_p_x1_address0);
    grp_psosc_Setup_fu_210->psosc_p_x1_ce0(grp_psosc_Setup_fu_210_psosc_p_x1_ce0);
    grp_psosc_Setup_fu_210->psosc_p_x1_we0(grp_psosc_Setup_fu_210_psosc_p_x1_we0);
    grp_psosc_Setup_fu_210->psosc_p_x1_d0(grp_psosc_Setup_fu_210_psosc_p_x1_d0);
    grp_psosc_Setup_fu_210->psosc_p_x2_address0(grp_psosc_Setup_fu_210_psosc_p_x2_address0);
    grp_psosc_Setup_fu_210->psosc_p_x2_ce0(grp_psosc_Setup_fu_210_psosc_p_x2_ce0);
    grp_psosc_Setup_fu_210->psosc_p_x2_we0(grp_psosc_Setup_fu_210_psosc_p_x2_we0);
    grp_psosc_Setup_fu_210->psosc_p_x2_d0(grp_psosc_Setup_fu_210_psosc_p_x2_d0);
    grp_psosc_Setup_fu_210->psosc_p_v1_address0(grp_psosc_Setup_fu_210_psosc_p_v1_address0);
    grp_psosc_Setup_fu_210->psosc_p_v1_ce0(grp_psosc_Setup_fu_210_psosc_p_v1_ce0);
    grp_psosc_Setup_fu_210->psosc_p_v1_we0(grp_psosc_Setup_fu_210_psosc_p_v1_we0);
    grp_psosc_Setup_fu_210->psosc_p_v1_d0(grp_psosc_Setup_fu_210_psosc_p_v1_d0);
    grp_psosc_Setup_fu_210->psosc_p_v2_address0(grp_psosc_Setup_fu_210_psosc_p_v2_address0);
    grp_psosc_Setup_fu_210->psosc_p_v2_ce0(grp_psosc_Setup_fu_210_psosc_p_v2_ce0);
    grp_psosc_Setup_fu_210->psosc_p_v2_we0(grp_psosc_Setup_fu_210_psosc_p_v2_we0);
    grp_psosc_Setup_fu_210->psosc_p_v2_d0(grp_psosc_Setup_fu_210_psosc_p_v2_d0);
    grp_psosc_Setup_fu_210->psosc_p_x1_best_address0(grp_psosc_Setup_fu_210_psosc_p_x1_best_address0);
    grp_psosc_Setup_fu_210->psosc_p_x1_best_ce0(grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0);
    grp_psosc_Setup_fu_210->psosc_p_x1_best_we0(grp_psosc_Setup_fu_210_psosc_p_x1_best_we0);
    grp_psosc_Setup_fu_210->psosc_p_x1_best_d0(grp_psosc_Setup_fu_210_psosc_p_x1_best_d0);
    grp_psosc_Setup_fu_210->psosc_p_x2_best_address0(grp_psosc_Setup_fu_210_psosc_p_x2_best_address0);
    grp_psosc_Setup_fu_210->psosc_p_x2_best_ce0(grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0);
    grp_psosc_Setup_fu_210->psosc_p_x2_best_we0(grp_psosc_Setup_fu_210_psosc_p_x2_best_we0);
    grp_psosc_Setup_fu_210->psosc_p_x2_best_d0(grp_psosc_Setup_fu_210_psosc_p_x2_best_d0);

    SC_METHOD(thread_complete);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_finalx1);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_finalx2);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_calculationDone);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_negFormula);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_setupDone);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_w);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_x1_global);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_psosc_x2_global);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_psosc_Execute_fu_130_psosc_calculationDone_i);
    sensitive << ( psosc_ssdm_thread_load_fu_266_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( psosc_calculationDone );

    SC_METHOD(thread_grp_psosc_Execute_fu_130_psosc_negFormula);
    sensitive << ( psosc_ssdm_thread_load_fu_266_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( psosc_negFormula );

    SC_METHOD(thread_grp_psosc_Execute_fu_130_psosc_setupDone);
    sensitive << ( psosc_ssdm_thread_load_fu_266_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( psosc_setupDone );

    SC_METHOD(thread_grp_psosc_Setup_fu_210_psosc_setupDone_i);
    sensitive << ( psosc_ssdm_thread_load_fu_266_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( psosc_setupDone );

    SC_METHOD(thread_psosc_p_v1_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_ce0 );

    SC_METHOD(thread_psosc_p_v1_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_ce0 );

    SC_METHOD(thread_psosc_p_v1_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_d0 );

    SC_METHOD(thread_psosc_p_v1_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v1_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v1_we0 );

    SC_METHOD(thread_psosc_p_v2_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_ce0 );

    SC_METHOD(thread_psosc_p_v2_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_ce0 );

    SC_METHOD(thread_psosc_p_v2_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_d0 );

    SC_METHOD(thread_psosc_p_v2_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_v2_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_v2_we0 );

    SC_METHOD(thread_psosc_p_x1_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_ce0 );

    SC_METHOD(thread_psosc_p_x1_best_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0 );

    SC_METHOD(thread_psosc_p_x1_best_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0 );

    SC_METHOD(thread_psosc_p_x1_best_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_d0 );

    SC_METHOD(thread_psosc_p_x1_best_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_best_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_best_we0 );

    SC_METHOD(thread_psosc_p_x1_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_ce0 );

    SC_METHOD(thread_psosc_p_x1_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_d0 );

    SC_METHOD(thread_psosc_p_x1_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x1_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x1_we0 );

    SC_METHOD(thread_psosc_p_x2_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_ce0 );

    SC_METHOD(thread_psosc_p_x2_best_address0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_address0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_address0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0 );

    SC_METHOD(thread_psosc_p_x2_best_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0 );

    SC_METHOD(thread_psosc_p_x2_best_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_d0 );

    SC_METHOD(thread_psosc_p_x2_best_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_best_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_best_we0 );

    SC_METHOD(thread_psosc_p_x2_ce0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_ce0 );

    SC_METHOD(thread_psosc_p_x2_d0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_d0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_d0 );

    SC_METHOD(thread_psosc_p_x2_we0);
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Execute_fu_130_psosc_p_x2_we0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_ce0 );
    sensitive << ( grp_psosc_Setup_fu_210_psosc_p_x2_we0 );

    SC_METHOD(thread_psosc_ssdm_thread_load_fu_266_p1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( clk.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "psosc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clk, "(port)clk");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, start, "(port)start");
    sc_trace(mVcdFile, negativeFormula, "(port)negativeFormula");
    sc_trace(mVcdFile, c1, "(port)c1");
    sc_trace(mVcdFile, c2, "(port)c2");
    sc_trace(mVcdFile, finalx1, "(port)finalx1");
    sc_trace(mVcdFile, finalx2, "(port)finalx2");
    sc_trace(mVcdFile, complete, "(port)complete");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, psosc_p_x1_address0, "psosc_p_x1_address0");
    sc_trace(mVcdFile, psosc_p_x1_ce0, "psosc_p_x1_ce0");
    sc_trace(mVcdFile, psosc_p_x1_we0, "psosc_p_x1_we0");
    sc_trace(mVcdFile, psosc_p_x1_d0, "psosc_p_x1_d0");
    sc_trace(mVcdFile, psosc_p_x1_q0, "psosc_p_x1_q0");
    sc_trace(mVcdFile, psosc_p_x2_address0, "psosc_p_x2_address0");
    sc_trace(mVcdFile, psosc_p_x2_ce0, "psosc_p_x2_ce0");
    sc_trace(mVcdFile, psosc_p_x2_we0, "psosc_p_x2_we0");
    sc_trace(mVcdFile, psosc_p_x2_d0, "psosc_p_x2_d0");
    sc_trace(mVcdFile, psosc_p_x2_q0, "psosc_p_x2_q0");
    sc_trace(mVcdFile, psosc_p_v1_address0, "psosc_p_v1_address0");
    sc_trace(mVcdFile, psosc_p_v1_ce0, "psosc_p_v1_ce0");
    sc_trace(mVcdFile, psosc_p_v1_we0, "psosc_p_v1_we0");
    sc_trace(mVcdFile, psosc_p_v1_d0, "psosc_p_v1_d0");
    sc_trace(mVcdFile, psosc_p_v1_q0, "psosc_p_v1_q0");
    sc_trace(mVcdFile, psosc_p_v2_address0, "psosc_p_v2_address0");
    sc_trace(mVcdFile, psosc_p_v2_ce0, "psosc_p_v2_ce0");
    sc_trace(mVcdFile, psosc_p_v2_we0, "psosc_p_v2_we0");
    sc_trace(mVcdFile, psosc_p_v2_d0, "psosc_p_v2_d0");
    sc_trace(mVcdFile, psosc_p_v2_q0, "psosc_p_v2_q0");
    sc_trace(mVcdFile, psosc_p_x1_best_address0, "psosc_p_x1_best_address0");
    sc_trace(mVcdFile, psosc_p_x1_best_ce0, "psosc_p_x1_best_ce0");
    sc_trace(mVcdFile, psosc_p_x1_best_we0, "psosc_p_x1_best_we0");
    sc_trace(mVcdFile, psosc_p_x1_best_d0, "psosc_p_x1_best_d0");
    sc_trace(mVcdFile, psosc_p_x1_best_q0, "psosc_p_x1_best_q0");
    sc_trace(mVcdFile, psosc_p_x2_best_address0, "psosc_p_x2_best_address0");
    sc_trace(mVcdFile, psosc_p_x2_best_ce0, "psosc_p_x2_best_ce0");
    sc_trace(mVcdFile, psosc_p_x2_best_we0, "psosc_p_x2_best_we0");
    sc_trace(mVcdFile, psosc_p_x2_best_d0, "psosc_p_x2_best_d0");
    sc_trace(mVcdFile, psosc_p_x2_best_q0, "psosc_p_x2_best_q0");
    sc_trace(mVcdFile, psosc_ssdm_thread_load_fu_266_p1, "psosc_ssdm_thread_load_fu_266_p1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_finalx1, "grp_psosc_Execute_fu_130_finalx1");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_finalx1_ap_vld, "grp_psosc_Execute_fu_130_finalx1_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_finalx2, "grp_psosc_Execute_fu_130_finalx2");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_finalx2_ap_vld, "grp_psosc_Execute_fu_130_finalx2_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_complete, "grp_psosc_Execute_fu_130_complete");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_complete_ap_vld, "grp_psosc_Execute_fu_130_complete_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_setupDone, "grp_psosc_Execute_fu_130_psosc_setupDone");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_calculationDone_i, "grp_psosc_Execute_fu_130_psosc_calculationDone_i");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_calculationDone_o, "grp_psosc_Execute_fu_130_psosc_calculationDone_o");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld, "grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_negFormula, "grp_psosc_Execute_fu_130_psosc_negFormula");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_iterations, "grp_psosc_Execute_fu_130_psosc_iterations");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_iterations_ap_vld, "grp_psosc_Execute_fu_130_psosc_iterations_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_x1_global_o, "grp_psosc_Execute_fu_130_psosc_x1_global_o");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld, "grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_x2_global_o, "grp_psosc_Execute_fu_130_psosc_x2_global_o");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld, "grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_address0, "grp_psosc_Execute_fu_130_psosc_p_x1_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_ce0, "grp_psosc_Execute_fu_130_psosc_p_x1_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_we0, "grp_psosc_Execute_fu_130_psosc_p_x1_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_d0, "grp_psosc_Execute_fu_130_psosc_p_x1_d0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_address0, "grp_psosc_Execute_fu_130_psosc_p_x2_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_ce0, "grp_psosc_Execute_fu_130_psosc_p_x2_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_we0, "grp_psosc_Execute_fu_130_psosc_p_x2_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_d0, "grp_psosc_Execute_fu_130_psosc_p_x2_d0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v1_address0, "grp_psosc_Execute_fu_130_psosc_p_v1_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v1_ce0, "grp_psosc_Execute_fu_130_psosc_p_v1_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v1_we0, "grp_psosc_Execute_fu_130_psosc_p_v1_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v1_d0, "grp_psosc_Execute_fu_130_psosc_p_v1_d0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v2_address0, "grp_psosc_Execute_fu_130_psosc_p_v2_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v2_ce0, "grp_psosc_Execute_fu_130_psosc_p_v2_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v2_we0, "grp_psosc_Execute_fu_130_psosc_p_v2_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_v2_d0, "grp_psosc_Execute_fu_130_psosc_p_v2_d0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_best_address0, "grp_psosc_Execute_fu_130_psosc_p_x1_best_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0, "grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_best_we0, "grp_psosc_Execute_fu_130_psosc_p_x1_best_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x1_best_d0, "grp_psosc_Execute_fu_130_psosc_p_x1_best_d0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_best_address0, "grp_psosc_Execute_fu_130_psosc_p_x2_best_address0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0, "grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_best_we0, "grp_psosc_Execute_fu_130_psosc_p_x2_best_we0");
    sc_trace(mVcdFile, grp_psosc_Execute_fu_130_psosc_p_x2_best_d0, "grp_psosc_Execute_fu_130_psosc_p_x2_best_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_complete, "grp_psosc_Setup_fu_210_complete");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_complete_ap_vld, "grp_psosc_Setup_fu_210_complete_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_setupDone_i, "grp_psosc_Setup_fu_210_psosc_setupDone_i");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_setupDone_o, "grp_psosc_Setup_fu_210_psosc_setupDone_o");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld, "grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_negFormula, "grp_psosc_Setup_fu_210_psosc_negFormula");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld, "grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_c1_cog, "grp_psosc_Setup_fu_210_psosc_c1_cog");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld, "grp_psosc_Setup_fu_210_psosc_c1_cog_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_c2_soc, "grp_psosc_Setup_fu_210_psosc_c2_soc");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld, "grp_psosc_Setup_fu_210_psosc_c2_soc_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_w, "grp_psosc_Setup_fu_210_psosc_w");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_w_ap_vld, "grp_psosc_Setup_fu_210_psosc_w_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_ax, "grp_psosc_Setup_fu_210_psosc_ax");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_ax_ap_vld, "grp_psosc_Setup_fu_210_psosc_ax_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_av, "grp_psosc_Setup_fu_210_psosc_av");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_av_ap_vld, "grp_psosc_Setup_fu_210_psosc_av_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_x1_global, "grp_psosc_Setup_fu_210_psosc_x1_global");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld, "grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_x2_global, "grp_psosc_Setup_fu_210_psosc_x2_global");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld, "grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_address0, "grp_psosc_Setup_fu_210_psosc_p_x1_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_ce0, "grp_psosc_Setup_fu_210_psosc_p_x1_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_we0, "grp_psosc_Setup_fu_210_psosc_p_x1_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_d0, "grp_psosc_Setup_fu_210_psosc_p_x1_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_address0, "grp_psosc_Setup_fu_210_psosc_p_x2_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_ce0, "grp_psosc_Setup_fu_210_psosc_p_x2_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_we0, "grp_psosc_Setup_fu_210_psosc_p_x2_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_d0, "grp_psosc_Setup_fu_210_psosc_p_x2_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v1_address0, "grp_psosc_Setup_fu_210_psosc_p_v1_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v1_ce0, "grp_psosc_Setup_fu_210_psosc_p_v1_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v1_we0, "grp_psosc_Setup_fu_210_psosc_p_v1_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v1_d0, "grp_psosc_Setup_fu_210_psosc_p_v1_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v2_address0, "grp_psosc_Setup_fu_210_psosc_p_v2_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v2_ce0, "grp_psosc_Setup_fu_210_psosc_p_v2_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v2_we0, "grp_psosc_Setup_fu_210_psosc_p_v2_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_v2_d0, "grp_psosc_Setup_fu_210_psosc_p_v2_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_best_address0, "grp_psosc_Setup_fu_210_psosc_p_x1_best_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0, "grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_best_we0, "grp_psosc_Setup_fu_210_psosc_p_x1_best_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x1_best_d0, "grp_psosc_Setup_fu_210_psosc_p_x1_best_d0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_best_address0, "grp_psosc_Setup_fu_210_psosc_p_x2_best_address0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0, "grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_best_we0, "grp_psosc_Setup_fu_210_psosc_p_x2_best_we0");
    sc_trace(mVcdFile, grp_psosc_Setup_fu_210_psosc_p_x2_best_d0, "grp_psosc_Setup_fu_210_psosc_p_x2_best_d0");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, psosc_setupDone, "psosc_setupDone");
    sc_trace(mVcdFile, psosc_calculationDone, "psosc_calculationDone");
    sc_trace(mVcdFile, psosc_negFormula, "psosc_negFormula");
    sc_trace(mVcdFile, psosc_w, "psosc_w");
    sc_trace(mVcdFile, psosc_x1_global, "psosc_x1_global");
    sc_trace(mVcdFile, psosc_x2_global, "psosc_x2_global");
#endif

    }
    mHdltvinHandle.open("psosc.hdltvin.dat");
    mHdltvoutHandle.open("psosc.hdltvout.dat");
}

psosc::~psosc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete psosc_p_x1_U;
    delete psosc_p_x2_U;
    delete psosc_p_v1_U;
    delete psosc_p_v2_U;
    delete psosc_p_x1_best_U;
    delete psosc_p_x2_best_U;
    delete grp_psosc_Execute_fu_130;
    delete grp_psosc_Setup_fu_210;
}

void psosc::thread_complete() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_complete_ap_vld.read())) {
        complete = grp_psosc_Setup_fu_210_complete.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_complete_ap_vld.read())) {
        complete = grp_psosc_Execute_fu_130_complete.read();
    }
}

void psosc::thread_finalx1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_finalx1_ap_vld.read())) {
        finalx1 = grp_psosc_Execute_fu_130_finalx1.read();
    }
}

void psosc::thread_finalx2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_finalx2_ap_vld.read())) {
        finalx2 = grp_psosc_Execute_fu_130_finalx2.read();
    }
}

void psosc::thread_psosc_calculationDone() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_calculationDone_o_ap_vld.read())) {
        psosc_calculationDone =  (sc_lv<1>) (grp_psosc_Execute_fu_130_psosc_calculationDone_o.read());
    }
}

void psosc::thread_psosc_negFormula() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_negFormula_ap_vld.read())) {
        psosc_negFormula =  (sc_lv<1>) (grp_psosc_Setup_fu_210_psosc_negFormula.read());
    }
}

void psosc::thread_psosc_setupDone() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_setupDone_o_ap_vld.read())) {
        psosc_setupDone =  (sc_lv<1>) (grp_psosc_Setup_fu_210_psosc_setupDone_o.read());
    }
}

void psosc::thread_psosc_w() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_w_ap_vld.read())) {
        psosc_w = grp_psosc_Setup_fu_210_psosc_w.read();
    }
}

void psosc::thread_psosc_x1_global() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_x1_global_ap_vld.read())) {
        psosc_x1_global = grp_psosc_Setup_fu_210_psosc_x1_global.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_x1_global_o_ap_vld.read())) {
        psosc_x1_global = grp_psosc_Execute_fu_130_psosc_x1_global_o.read();
    }
}

void psosc::thread_psosc_x2_global() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_x2_global_ap_vld.read())) {
        psosc_x2_global = grp_psosc_Setup_fu_210_psosc_x2_global.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_x2_global_o_ap_vld.read())) {
        psosc_x2_global = grp_psosc_Execute_fu_130_psosc_x2_global_o.read();
    }
}

void psosc::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_const_lv2_0;
}

void psosc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void psosc::thread_grp_psosc_Execute_fu_130_psosc_calculationDone_i() {
    grp_psosc_Execute_fu_130_psosc_calculationDone_i =  (sc_logic) (psosc_calculationDone.read()[0]);
}

void psosc::thread_grp_psosc_Execute_fu_130_psosc_negFormula() {
    grp_psosc_Execute_fu_130_psosc_negFormula =  (sc_logic) (psosc_negFormula.read()[0]);
}

void psosc::thread_grp_psosc_Execute_fu_130_psosc_setupDone() {
    grp_psosc_Execute_fu_130_psosc_setupDone =  (sc_logic) (psosc_setupDone.read()[0]);
}

void psosc::thread_grp_psosc_Setup_fu_210_psosc_setupDone_i() {
    grp_psosc_Setup_fu_210_psosc_setupDone_i =  (sc_logic) (psosc_setupDone.read()[0]);
}

void psosc::thread_psosc_p_v1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v1_ce0.read())) {
        psosc_p_v1_address0 = grp_psosc_Setup_fu_210_psosc_p_v1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v1_ce0.read())) {
        psosc_p_v1_address0 = grp_psosc_Execute_fu_130_psosc_p_v1_address0.read();
    } else {
        psosc_p_v1_address0 = "XX";
    }
}

void psosc::thread_psosc_p_v1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v1_ce0.read())) {
        psosc_p_v1_ce0 = grp_psosc_Setup_fu_210_psosc_p_v1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v1_ce0.read())) {
        psosc_p_v1_ce0 = grp_psosc_Execute_fu_130_psosc_p_v1_ce0.read();
    } else {
        psosc_p_v1_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_v1_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v1_ce0.read())) {
        psosc_p_v1_d0 = grp_psosc_Setup_fu_210_psosc_p_v1_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v1_ce0.read())) {
        psosc_p_v1_d0 = grp_psosc_Execute_fu_130_psosc_p_v1_d0.read();
    } else {
        psosc_p_v1_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_v1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v1_ce0.read())) {
        psosc_p_v1_we0 = grp_psosc_Setup_fu_210_psosc_p_v1_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v1_ce0.read())) {
        psosc_p_v1_we0 = grp_psosc_Execute_fu_130_psosc_p_v1_we0.read();
    } else {
        psosc_p_v1_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_v2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v2_ce0.read())) {
        psosc_p_v2_address0 = grp_psosc_Setup_fu_210_psosc_p_v2_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v2_ce0.read())) {
        psosc_p_v2_address0 = grp_psosc_Execute_fu_130_psosc_p_v2_address0.read();
    } else {
        psosc_p_v2_address0 = "XX";
    }
}

void psosc::thread_psosc_p_v2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v2_ce0.read())) {
        psosc_p_v2_ce0 = grp_psosc_Setup_fu_210_psosc_p_v2_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v2_ce0.read())) {
        psosc_p_v2_ce0 = grp_psosc_Execute_fu_130_psosc_p_v2_ce0.read();
    } else {
        psosc_p_v2_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_v2_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v2_ce0.read())) {
        psosc_p_v2_d0 = grp_psosc_Setup_fu_210_psosc_p_v2_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v2_ce0.read())) {
        psosc_p_v2_d0 = grp_psosc_Execute_fu_130_psosc_p_v2_d0.read();
    } else {
        psosc_p_v2_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_v2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_v2_ce0.read())) {
        psosc_p_v2_we0 = grp_psosc_Setup_fu_210_psosc_p_v2_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_v2_ce0.read())) {
        psosc_p_v2_we0 = grp_psosc_Execute_fu_130_psosc_p_v2_we0.read();
    } else {
        psosc_p_v2_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_ce0.read())) {
        psosc_p_x1_address0 = grp_psosc_Setup_fu_210_psosc_p_x1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_ce0.read())) {
        psosc_p_x1_address0 = grp_psosc_Execute_fu_130_psosc_p_x1_address0.read();
    } else {
        psosc_p_x1_address0 = "XX";
    }
}

void psosc::thread_psosc_p_x1_best_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_address0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_address0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_address0.read();
    } else {
        psosc_p_x1_best_address0 = "XX";
    }
}

void psosc::thread_psosc_p_x1_best_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_ce0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_ce0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0.read();
    } else {
        psosc_p_x1_best_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x1_best_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_d0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_d0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_d0.read();
    } else {
        psosc_p_x1_best_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_x1_best_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_we0 = grp_psosc_Setup_fu_210_psosc_p_x1_best_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_best_ce0.read())) {
        psosc_p_x1_best_we0 = grp_psosc_Execute_fu_130_psosc_p_x1_best_we0.read();
    } else {
        psosc_p_x1_best_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_ce0.read())) {
        psosc_p_x1_ce0 = grp_psosc_Setup_fu_210_psosc_p_x1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_ce0.read())) {
        psosc_p_x1_ce0 = grp_psosc_Execute_fu_130_psosc_p_x1_ce0.read();
    } else {
        psosc_p_x1_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x1_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_ce0.read())) {
        psosc_p_x1_d0 = grp_psosc_Setup_fu_210_psosc_p_x1_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_ce0.read())) {
        psosc_p_x1_d0 = grp_psosc_Execute_fu_130_psosc_p_x1_d0.read();
    } else {
        psosc_p_x1_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_x1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x1_ce0.read())) {
        psosc_p_x1_we0 = grp_psosc_Setup_fu_210_psosc_p_x1_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x1_ce0.read())) {
        psosc_p_x1_we0 = grp_psosc_Execute_fu_130_psosc_p_x1_we0.read();
    } else {
        psosc_p_x1_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_ce0.read())) {
        psosc_p_x2_address0 = grp_psosc_Setup_fu_210_psosc_p_x2_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_ce0.read())) {
        psosc_p_x2_address0 = grp_psosc_Execute_fu_130_psosc_p_x2_address0.read();
    } else {
        psosc_p_x2_address0 = "XX";
    }
}

void psosc::thread_psosc_p_x2_best_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_address0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_address0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_address0.read();
    } else {
        psosc_p_x2_best_address0 = "XX";
    }
}

void psosc::thread_psosc_p_x2_best_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_ce0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_ce0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0.read();
    } else {
        psosc_p_x2_best_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x2_best_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_d0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_d0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_d0.read();
    } else {
        psosc_p_x2_best_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_x2_best_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_we0 = grp_psosc_Setup_fu_210_psosc_p_x2_best_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_best_ce0.read())) {
        psosc_p_x2_best_we0 = grp_psosc_Execute_fu_130_psosc_p_x2_best_we0.read();
    } else {
        psosc_p_x2_best_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_ce0.read())) {
        psosc_p_x2_ce0 = grp_psosc_Setup_fu_210_psosc_p_x2_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_ce0.read())) {
        psosc_p_x2_ce0 = grp_psosc_Execute_fu_130_psosc_p_x2_ce0.read();
    } else {
        psosc_p_x2_ce0 = sc_logic('X');
    }
}

void psosc::thread_psosc_p_x2_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_ce0.read())) {
        psosc_p_x2_d0 = grp_psosc_Setup_fu_210_psosc_p_x2_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_ce0.read())) {
        psosc_p_x2_d0 = grp_psosc_Execute_fu_130_psosc_p_x2_d0.read();
    } else {
        psosc_p_x2_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void psosc::thread_psosc_p_x2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Setup_fu_210_psosc_p_x2_ce0.read())) {
        psosc_p_x2_we0 = grp_psosc_Setup_fu_210_psosc_p_x2_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_psosc_Execute_fu_130_psosc_p_x2_ce0.read())) {
        psosc_p_x2_we0 = grp_psosc_Execute_fu_130_psosc_p_x2_we0.read();
    } else {
        psosc_p_x2_we0 = sc_logic('X');
    }
}

void psosc::thread_psosc_ssdm_thread_load_fu_266_p1() {
    psosc_ssdm_thread_load_fu_266_p1 = ap_const_lv1_0;
}

void psosc::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"reset\" :  \"" << reset.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"start\" :  \"" << start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"negativeFormula\" :  \"" << negativeFormula.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"c1\" :  \"" << c1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"c2\" :  \"" << c2.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"finalx1\" :  \"" << finalx1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"finalx2\" :  \"" << finalx2.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"complete\" :  \"" << complete.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

